/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck -- pointer-driven canvas uses guarded array mutations that strict indexed access cannot infer.
"use client";
import{ChangeEvent,PointerEvent,useEffect,useRef,useState}from"react";
import{Locale}from"@/lib/i18n";

type ElementType="text"|"shape"|"image";
type CanvasElement={id:string;type:ElementType;x:number;y:number;width:number;height:number;text?:string;fontSize?:number;fontFamily?:string;fontWeight?:number;color?:string;align?:"left"|"center"|"right";shape?:"rect"|"circle"|"line";fill?:string;stroke?:string;strokeWidth?:number;src?:string};
type Template={id:string;name:string;documentType:"ASSIGNMENT"|"PRESCRIPTION"|"RECEIPT"|"OTHER";pageSize:"A4"|"A5"|"RECEIPT_80"|"CUSTOM";widthMm:number;heightMm:number;layout:{elements:CanvasElement[]};isDefault:boolean};
const uid=()=>crypto.randomUUID();
const blank=():Template=>({id:"",name:"Новый шаблон",documentType:"ASSIGNMENT",pageSize:"A4",widthMm:210,heightMm:297,layout:{elements:[]},isDefault:false});
const presets={A4:[210,297],A5:[148,210],RECEIPT_80:[80,200]} as const;
const variables=["{{patient.fullName}}","{{patient.birthDate}}","{{doctor.fullName}}","{{diagnosis}}","{{assignment}}","{{date}}","{{branch.name}}","{{receipt.total}}"];

export function DocumentTemplateBuilder({locale:_locale}:{locale:Locale}){
 const[items,setItems]=useState<Template[]>([]),[draft,setDraft]=useState<Template|null>(null),[selected,setSelected]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false),[preview,setPreview]=useState(false);const canvas=useRef<HTMLDivElement>(null),drag=useRef<{id:string;mode:"move"|"resize";sx:number;sy:number;start:CanvasElement}|null>(null);
 const load=async()=>{const r=await fetch("/api/clinic/document-templates",{cache:"no-store"});if(!r.ok){setError("Не удалось загрузить шаблоны");return}const d=await r.json();setItems(d.items??[])};useEffect(()=>{void load()},[]);
 const update=(patch:Partial<Template>)=>setDraft(d=>d?{...d,...patch}:d);const updateElement=(id:string,patch:Partial<CanvasElement>)=>setDraft(d=>d?{...d,layout:{elements:d.layout.elements.map(e=>e.id===id?{...e,...patch}:e)}}:d);
 const add=(type:ElementType,shape?:CanvasElement["shape"])=>{const id=uid();const e:CanvasElement=type==="text"?{id,type,x:10,y:10,width:35,height:8,text:"Новый текст",fontSize:14,fontFamily:"Manrope",fontWeight:500,color:"#17202a",align:"left"}:type==="image"?{id,type,x:10,y:10,width:16,height:12,src:"/brand-mark.png"}:{id,type,x:10,y:10,width:25,height:shape==="line"?1:12,shape:shape??"rect",fill:shape==="line"?"transparent":"#fff0f4",stroke:"#e80d4f",strokeWidth:2};setDraft(d=>d?{...d,layout:{elements:[...d.layout.elements,e]}}:d);setSelected(id)};
 const pointerDown=(ev:PointerEvent,id:string,mode:"move"|"resize")=>{ev.preventDefault();ev.stopPropagation();const e=draft?.layout.elements.find(x=>x.id===id);if(!e)return;setSelected(id);drag.current={id,mode,sx:ev.clientX,sy:ev.clientY,start:{...e}};(ev.currentTarget as HTMLElement).setPointerCapture(ev.pointerId)};
 const pointerMove=(ev:PointerEvent)=>{const d=drag.current,b=canvas.current?.getBoundingClientRect();if(!d||!b)return;const dx=(ev.clientX-d.sx)/b.width*100,dy=(ev.clientY-d.sy)/b.height*100;if(d.mode==="move")updateElement(d.id,{x:Math.max(0,Math.min(100-d.start.width,d.start.x+dx)),y:Math.max(0,Math.min(100-d.start.height,d.start.y+dy))});else updateElement(d.id,{width:Math.max(3,Math.min(100-d.start.x,d.start.width+dx)),height:Math.max(.7,Math.min(100-d.start.y,d.start.height+dy))})};
 const save=async()=>{if(!draft||draft.name.trim().length<2)return setError("Введите название шаблона");setSaving(true);setError("");const r=await fetch(`/api/clinic/document-templates${draft.id?`/${draft.id}`:""}`,{method:draft.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(draft)});setSaving(false);if(!r.ok){setError("Не удалось сохранить шаблон");return}await load();setDraft(null)};
 const remove=async()=>{if(!draft?.id||!confirm("Удалить этот шаблон?"))return;const r=await fetch(`/api/clinic/document-templates/${draft.id}`,{method:"DELETE"});if(!r.ok)return setError("Не удалось удалить шаблон");setDraft(null);await load()};
 const pageChange=(v:Template["pageSize"])=>{const p=v==="CUSTOM"?null:presets[v];update({pageSize:v,...(p?{widthMm:p[0],heightMm:p[1]}:{})})};
 const upload=(ev:ChangeEvent<HTMLInputElement>)=>{const f=ev.target.files?.[0];if(!f)return;if(!f.type.startsWith("image/")||f.size>1500000){setError("Логотип должен быть изображением до 1,5 МБ");return}const reader=new FileReader();reader.onload=()=>{const id=uid(),image:CanvasElement={id,type:"image",x:10,y:10,width:16,height:12,src:String(reader.result)};setDraft(d=>d?{...d,layout:{elements:[...d.layout.elements,image]}}:d);setSelected(id)};reader.readAsDataURL(f)};
 const active=draft?.layout.elements.find(e=>e.id===selected);
 return <section className="template-builder"><div className="management-head"><div><p>ПЕЧАТНЫЕ ФОРМЫ</p><h1>Конструктор документов</h1><span>Шаблоны назначений, рецептов и чеков</span></div><button className="primary" onClick={()=>setDraft(blank())}>+ Новый шаблон</button></div>{error&&<div className="management-error">{error}</div>}
 {!draft?<div className="template-list">{items.map(t=><button key={t.id} onClick={()=>{setDraft(structuredClone(t));setSelected("")}}><strong>{t.name}</strong><span>{({ASSIGNMENT:"Назначение",PRESCRIPTION:"Рецепт",RECEIPT:"Чек",OTHER:"Другой"} as const)[t.documentType]} · {t.widthMm} × {t.heightMm} мм</span>{t.isDefault&&<b>По умолчанию</b>}</button>)}{!items.length&&<div className="table-empty">Шаблонов пока нет</div>}</div>:
 <div className="designer-shell"><aside className="designer-tools"><h3>Документ</h3><label>Название<input value={draft.name} onChange={e=>update({name:e.target.value})}/></label><label>Тип<select value={draft.documentType} onChange={e=>update({documentType:e.target.value as Template["documentType"]})}><option value="ASSIGNMENT">Назначение</option><option value="PRESCRIPTION">Рецепт</option><option value="RECEIPT">Чек</option><option value="OTHER">Другой</option></select></label><label>Размер листа<select value={draft.pageSize} onChange={e=>pageChange(e.target.value as Template["pageSize"])}><option value="A4">A4</option><option value="A5">A5</option><option value="RECEIPT_80">Чек 80 мм</option><option value="CUSTOM">Свой размер</option></select></label><div className="size-row"><label>Ширина, мм<input type="number" min="40" max="500" value={draft.widthMm} onChange={e=>update({widthMm:+e.target.value})}/></label><label>Высота, мм<input type="number" min="40" max="1000" value={draft.heightMm} onChange={e=>update({heightMm:+e.target.value})}/></label></div><label className="check"><input type="checkbox" checked={draft.isDefault} onChange={e=>update({isDefault:e.target.checked})}/> Использовать по умолчанию</label><h3>Добавить</h3><div className="tool-grid"><button onClick={()=>add("text")}>Текст</button><label className="file-tool">Логотип<input type="file" accept="image/*" onChange={upload}/></label><button onClick={()=>add("shape","rect")}>Прямоугольник</button><button onClick={()=>add("shape","circle")}>Круг</button><button onClick={()=>add("shape","line")}>Линия</button></div><h3>Переменные</h3><div className="variables">{variables.map(v=><button key={v} onClick={()=>{add("text");setDraft(d=>{if(!d)return d;const es=[...d.layout.elements];es[es.length-1]={...es[es.length-1],text:v};return{...d,layout:{elements:es}}})}}>{v}</button>)}</div></aside>
 <main className="designer-stage"><div className="canvas-wrap"><div ref={canvas} className="paper" style={{aspectRatio:`${draft.widthMm}/${draft.heightMm}`}} onPointerMove={pointerMove} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null} onPointerDown={()=>setSelected("")}>{draft.layout.elements.map(e=><CanvasItem key={e.id} element={e} selected={selected===e.id} onSelect={ev=>pointerDown(ev,e.id,"move")} onResize={ev=>pointerDown(ev,e.id,"resize")}/>)}</div></div></main>
 <aside className="property-panel"><h3>Свойства элемента</h3>{!active?<p>Выберите элемент на листе</p>:<>{active.type==="text"&&<><label>Текст<textarea value={active.text??""} onChange={e=>updateElement(active.id,{text:e.target.value})}/></label><label>Шрифт<select value={active.fontFamily} onChange={e=>updateElement(active.id,{fontFamily:e.target.value})}><option>Manrope</option><option>Arial</option><option>Times New Roman</option><option>Georgia</option></select></label><label>Размер<input type="number" min="6" max="72" value={active.fontSize} onChange={e=>updateElement(active.id,{fontSize:+e.target.value})}/></label><label>Цвет<input type="color" value={active.color} onChange={e=>updateElement(active.id,{color:e.target.value})}/></label><label>Начертание<select value={active.fontWeight} onChange={e=>updateElement(active.id,{fontWeight:+e.target.value})}><option value="400">Обычный</option><option value="600">Полужирный</option><option value="800">Жирный</option></select></label><label>Выравнивание<select value={active.align} onChange={e=>updateElement(active.id,{align:e.target.value as CanvasElement["align"]})}><option value="left">Слева</option><option value="center">По центру</option><option value="right">Справа</option></select></label></>}{active.type==="shape"&&<><label>Заливка<input type="color" value={active.fill==="transparent"?"#ffffff":active.fill} onChange={e=>updateElement(active.id,{fill:e.target.value})}/></label><label>Контур<input type="color" value={active.stroke} onChange={e=>updateElement(active.id,{stroke:e.target.value})}/></label><label>Толщина контура<input type="number" min="1" max="10" value={active.strokeWidth} onChange={e=>updateElement(active.id,{strokeWidth:+e.target.value})}/></label></>}<button className="danger-button" onClick={()=>{setDraft(d=>d?{...d,layout:{elements:d.layout.elements.filter(e=>e.id!==active.id)}}:d);setSelected("")}}>Удалить элемент</button></>}</aside>
 <footer className="designer-actions"><button className="secondary" onClick={()=>setDraft(null)}>Закрыть</button>{draft.id&&<button className="danger-button" onClick={remove}>Удалить шаблон</button>}<button className="secondary" onClick={()=>setPreview(true)}>Предпросмотр</button><button className="primary" disabled={saving} onClick={save}>{saving?"Сохранение…":"Сохранить шаблон"}</button></footer></div>}
 {preview&&draft&&<div className="print-overlay"><div className="print-toolbar"><button onClick={()=>setPreview(false)}>Закрыть</button><button className="primary" onClick={()=>window.print()}>Печать</button></div><div className="print-paper" style={{width:`${draft.widthMm}mm`,height:`${draft.heightMm}mm`}}>{draft.layout.elements.map(e=><CanvasItem key={e.id} element={e}/>)}</div></div>}</section>
}

function CanvasItem({element:e,selected,onSelect,onResize}:{element:CanvasElement;selected?:boolean;onSelect?:(e:PointerEvent)=>void;onResize?:(e:PointerEvent)=>void}){const style={left:`${e.x}%`,top:`${e.y}%`,width:`${e.width}%`,height:`${e.height}%`};return <div className={`canvas-element ${selected?"selected":""}`} style={style} onPointerDown={onSelect}>{e.type==="text"?<div className="canvas-text" style={{fontSize:e.fontSize,fontFamily:e.fontFamily,fontWeight:e.fontWeight,color:e.color,textAlign:e.align,whiteSpace:"pre-wrap"}}>{e.text}</div>:e.type==="image"?<img src={e.src} alt="" draggable={false}/>:<div className={`canvas-shape ${e.shape}`} style={{background:e.fill,borderColor:e.stroke,borderWidth:e.strokeWidth}}/>}{selected&&<i className="resize-handle" onPointerDown={onResize}/>}</div>}
