"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Locale } from "@/lib/i18n";

type Branch={id:string;name:string}; type Employee={id:string;firstName:string;lastName:string;isActive:boolean};
type Patient={id:string;firstName:string;lastName:string;middleName?:string|null;birthDate?:string};
type Bed={id:string;number:string;operationalStatus:string;bookingStatus:string;isActive:boolean};
type Room={id:string;branchId:string;branch:string;number:string;name:string;roomType:string;floor:number;patientGender:string;amenities:string;pricePerDayUzs:number;isActive:boolean;beds:Bed[]};
type Booking={id:string;bedId:string;bed:string;room:string;branch:string;patient:string;employee:string;checkIn:string;checkOut:string;status:string;pricePerDayUzs:number;depositUzs:number;discountUzs:number;notes:string};
const money=(v:number)=>new Intl.NumberFormat("ru-RU").format(v)+" сум";
const roomType:Record<string,string>={GENERAL:"Общая",STANDARD:"Стандарт",COMFORT:"Комфорт",LUX:"Люкс",ICU:"Реанимация",PEDIATRIC:"Детская",MATERNITY:"Послеродовая"};
const bedStatus:Record<string,string>={AVAILABLE:"Свободна",CLEANING:"Санитарная обработка",MAINTENANCE:"Ремонт",RESERVED:"Забронирована",CHECKED_IN:"Занята"};
const bookingStatus:Record<string,string>={RESERVED:"Забронировано",CHECKED_IN:"Заселён",DISCHARGED:"Выписан",CANCELLED:"Отменено"};

export function InpatientManagement({locale}:{locale:Locale}){
 const ru=locale==="ru"; const [tab,setTab]=useState<"rooms"|"bookings">("rooms"),[rooms,setRooms]=useState<Room[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[branches,setBranches]=useState<Branch[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[patients,setPatients]=useState<Patient[]>([]),[query,setQuery]=useState(""),[selectedPatient,setSelectedPatient]=useState<Patient|null>(null),[showRoom,setShowRoom]=useState(false),[editing,setEditing]=useState<Room|null>(null),[showBooking,setShowBooking]=useState(false),[error,setError]=useState("");
 const load=async()=>{const[r,b,br,e]=await Promise.all([fetch("/api/clinic/inpatient/rooms",{cache:"no-store"}),fetch("/api/clinic/inpatient/bookings",{cache:"no-store"}),fetch("/api/clinic/branches",{cache:"no-store"}),fetch("/api/clinic/employees",{cache:"no-store"})]);if(r.ok)setRooms((await r.json()).items??[]);if(b.ok)setBookings((await b.json()).items??[]);if(br.ok)setBranches((await br.json()).items??[]);if(e.ok)setEmployees((await e.json()).items??[])};
 useEffect(()=>{void load()},[]); useEffect(()=>{if(query.trim().length<2){setPatients([]);return}const timer=setTimeout(async()=>{const r=await fetch(`/api/clinic/patients?q=${encodeURIComponent(query)}`,{cache:"no-store"});if(r.ok)setPatients((await r.json()).items??[])},250);return()=>clearTimeout(timer)},[query]);
 const usableBeds=useMemo(()=>rooms.filter(r=>r.isActive).flatMap(r=>r.beds.filter(b=>b.isActive).map(b=>({room:r,bed:b}))),[rooms]);
 const saveRoom=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError("");const f=new FormData(e.currentTarget),body={branchId:f.get("branchId"),number:f.get("number"),name:f.get("name"),roomType:f.get("roomType"),floor:Number(f.get("floor")),patientGender:f.get("patientGender"),amenities:f.get("amenities"),pricePerDayUzs:Number(f.get("price")),bedCount:Number(f.get("bedCount")||0)};const r=await fetch(editing?`/api/clinic/inpatient/rooms/${editing.id}`:"/api/clinic/inpatient/rooms",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError(ru?"Не удалось сохранить палату. Проверьте номер и поля.":"Could not save room");return}setShowRoom(false);setEditing(null);await load()};
 const addBed=async(room:Room)=>{const number=window.prompt(ru?"Номер новой койки":"Bed number",String(room.beds.length+1));if(!number)return;const r=await fetch(`/api/clinic/inpatient/rooms/${room.id}/beds`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({number})});if(!r.ok)setError(ru?"Такая койка уже существует":"Bed already exists");else await load()};
 const setBedState=async(id:string,status:string)=>{await fetch(`/api/clinic/inpatient/beds/${id}/status`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})});await load()};
 const disableRoom=async(room:Room)=>{if(!confirm(`Отключить палату №${room.number}?`))return;const r=await fetch(`/api/clinic/inpatient/rooms/${room.id}`,{method:"DELETE"});if(!r.ok)setError("Нельзя отключить палату с активной бронью");else await load()};
 const saveBooking=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selectedPatient){setError("Выберите пациента из найденного списка");return}const f=new FormData(e.currentTarget);const body={bedId:f.get("bedId"),patientId:selectedPatient.id,employeeId:f.get("employeeId"),checkIn:new Date(String(f.get("checkIn"))).toISOString(),checkOut:new Date(String(f.get("checkOut"))).toISOString(),depositUzs:Number(f.get("deposit")||0),discountUzs:Number(f.get("discount")||0),notes:f.get("notes")};const r=await fetch("/api/clinic/inpatient/bookings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){const d=await r.json().catch(()=>null);setError(d?.error?.code==="booking_overlap"?"Эта койка уже забронирована на выбранные даты":"Проверьте данные бронирования");return}setShowBooking(false);setSelectedPatient(null);setQuery("");setTab("bookings");await load()};
 const setBookingState=async(id:string,status:string)=>{const r=await fetch(`/api/clinic/inpatient/bookings/${id}/status`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})});if(!r.ok)setError("Не удалось изменить статус");else await load()};
 return <section className="management inpatient"><div className="management-head"><div><p>СТАЦИОНАР</p><h1>Палаты и бронирование</h1><span>Управление палатами, койками, заселением и выпиской пациентов</span></div><button className="primary" onClick={()=>tab==="rooms"?(setEditing(null),setShowRoom(true)) : setShowBooking(true)}>+ {tab==="rooms"?"Добавить палату":"Новая бронь"}</button></div>
 <div className="inpatient-tabs"><button className={tab==="rooms"?"active":""} onClick={()=>setTab("rooms")}>Палаты и койки</button><button className={tab==="bookings"?"active":""} onClick={()=>setTab("bookings")}>Бронирования <b>{bookings.filter(x=>x.status==="RESERVED"||x.status==="CHECKED_IN").length}</b></button></div>{error&&<div className="management-error">{error}</div>}
 {showRoom&&<form className="admin-form" onSubmit={saveRoom}><label>Филиал<select name="branchId" required defaultValue={editing?.branchId||""}><option value="">—</option>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Номер палаты<input name="number" required defaultValue={editing?.number}/></label><label>Название<input name="name" defaultValue={editing?.name} placeholder="Например: Детская комфорт"/></label><label>Тип палаты<select name="roomType" defaultValue={editing?.roomType||"STANDARD"}>{Object.entries(roomType).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Этаж<input name="floor" type="number" min={-5} max={100} required defaultValue={editing?.floor??1}/></label><label>Для кого<select name="patientGender" defaultValue={editing?.patientGender||"ANY"}><option value="ANY">Для всех</option><option value="FEMALE">Женская</option><option value="MALE">Мужская</option><option value="CHILDREN">Детская</option></select></label><label>Цена за сутки, сум<input name="price" type="number" min={0} step={1000} required defaultValue={editing?.pricePerDayUzs??0}/></label>{!editing&&<label>Количество коек<input name="bedCount" type="number" min={1} max={50} required defaultValue={1}/></label>}<label className="service-description">Удобства и примечание<input name="amenities" defaultValue={editing?.amenities} placeholder="Санузел, кондиционер, телевизор…"/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>{setShowRoom(false);setEditing(null)}}>Отмена</button><button className="primary">Сохранить</button></div></form>}
 {showBooking&&<form className="admin-form inpatient-booking-form" onSubmit={saveBooking}><label className="patient-picker">Пациент<input value={query} onChange={e=>{setQuery(e.target.value);setSelectedPatient(null)}} placeholder="Введите имя или фамилию" required/>{patients.length>0&&!selectedPatient&&<span className="patient-options">{patients.map(x=><button type="button" key={x.id} onClick={()=>{setSelectedPatient(x);setQuery(`${x.lastName} ${x.firstName} ${x.middleName||""}`);setPatients([])}}>{x.lastName} {x.firstName} {x.middleName}</button>)}</span>}</label><label>Палата и койка<select name="bedId" required><option value="">—</option>{usableBeds.map(({room,bed})=><option key={bed.id} value={bed.id} disabled={bed.operationalStatus!=="AVAILABLE"}>№{room.number}, койка {bed.number} · {room.branch} · {money(room.pricePerDayUzs)}/сутки</option>)}</select></label><label>Дата и время заселения<input name="checkIn" type="datetime-local" required/></label><label>Плановая дата выписки<input name="checkOut" type="datetime-local" required/></label><label>Лечащий врач<select name="employeeId"><option value="">—</option>{employees.filter(x=>x.isActive).map(x=><option key={x.id} value={x.id}>{x.lastName} {x.firstName}</option>)}</select></label><label>Предоплата, сум<input name="deposit" type="number" min={0} step={1000} defaultValue={0}/></label><label>Скидка, сум<input name="discount" type="number" min={0} step={1000} defaultValue={0}/></label><label>Примечание<input name="notes"/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setShowBooking(false)}>Отмена</button><button className="primary">Забронировать</button></div></form>}
 {tab==="rooms"?<div className="room-grid">{rooms.length===0?<div className="table-empty">Палаты пока не добавлены</div>:rooms.map(room=><article key={room.id} className={!room.isActive?"disabled":""}><header><div><span>{room.branch} · {room.floor} этаж</span><h2>Палата №{room.number}{room.name?` — ${room.name}`:""}</h2><p>{roomType[room.roomType]||room.roomType} · {money(room.pricePerDayUzs)} за сутки</p></div><div className="service-actions"><button className="secondary" onClick={()=>{setEditing(room);setShowRoom(true)}}>Изменить</button><button className="secondary" onClick={()=>void addBed(room)}>+ Койка</button>{room.isActive&&<button className="danger-button" onClick={()=>void disableRoom(room)}>Отключить</button>}</div></header>{room.amenities&&<p className="room-amenities">{room.amenities}</p>}<div className="bed-list">{room.beds.filter(x=>x.isActive).map(b=>{const state=b.bookingStatus||b.operationalStatus;return <div key={b.id} className={`bed ${state.toLowerCase()}`}><strong>Койка {b.number}</strong><span>{bedStatus[state]||state}</span>{!b.bookingStatus&&<select value={b.operationalStatus} onChange={e=>void setBedState(b.id,e.target.value)}><option value="AVAILABLE">Свободна</option><option value="CLEANING">Санитарная обработка</option><option value="MAINTENANCE">Ремонт</option></select>}</div>})}</div></article>)}</div>:<div className="booking-list">{bookings.length===0?<div className="table-empty">Бронирований пока нет</div>:bookings.map(x=>{const days=Math.max(1,Math.ceil((new Date(x.checkOut).getTime()-new Date(x.checkIn).getTime())/86400000)),total=Math.max(0,days*x.pricePerDayUzs-x.discountUzs);return <article key={x.id}><div className="booking-patient"><span className={`booking-status ${x.status.toLowerCase()}`}>{bookingStatus[x.status]||x.status}</span><h2>{x.patient}</h2><p>{x.branch} · палата №{x.room}, койка {x.bed}</p></div><div><strong>{new Date(x.checkIn).toLocaleString("ru-RU")}</strong><span>до {new Date(x.checkOut).toLocaleString("ru-RU")} · {days} сут.</span></div><div><strong>{money(total)}</strong><span>Предоплата: {money(x.depositUzs)}</span></div><select value={x.status} onChange={e=>void setBookingState(x.id,e.target.value)}><option value="RESERVED">Забронировано</option><option value="CHECKED_IN">Заселён</option><option value="DISCHARGED">Выписан</option><option value="CANCELLED">Отменено</option></select></article>})}</div>}</section>
}
