"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Locale} from "@/lib/i18n";

type Test={id:string;name:string;code?:string|null;specimen:string;description?:string|null;isActive:boolean;priceUzs:number};
type Patient={id:string;firstName:string;lastName:string;middleName?:string|null};
type Branch={id:string;name:string}; type Employee={id:string;firstName:string;lastName:string;isActive:boolean};
type Item={id:string;testId:string;name:string;code?:string|null;specimen:string;result?:string|null;unit?:string|null;referenceRange?:string|null};
type Order={id:string;status:string;priority:string;clinicalNote?:string|null;resultNote?:string|null;source:string;createdAt:string;completedAt?:string|null;attachmentId?:string|null;patient:{id:string;name:string};branch:{id:string;name:string};employee:{id?:string|null;name?:string|null};items:Item[]};
const status:Record<string,string>={NEW:"Новое",SAMPLE_COLLECTED:"Материал принят",IN_PROGRESS:"В работе",COMPLETED:"Результат готов",CANCELLED:"Отменено"};
const nextStatus:Record<string,string|undefined>={NEW:"SAMPLE_COLLECTED",SAMPLE_COLLECTED:"IN_PROGRESS"};

async function attachment(file:File){
 if(file.size>10*1024*1024)throw new Error("Файл больше 10 МБ");
 if(!["image/jpeg","image/png","image/webp","application/pdf"].includes(file.type))throw new Error("Разрешены JPG, PNG, WEBP или PDF");
 let quality="not_checked";
 if(file.type.startsWith("image/")){const bitmap=await createImageBitmap(file);if(bitmap.width<1000||bitmap.height<700){bitmap.close();throw new Error("Фото слишком маленькое. Сфотографируйте результат заново ближе и чётче")};const canvas=document.createElement("canvas"),size=160;canvas.width=size;canvas.height=size;const ctx=canvas.getContext("2d",{willReadFrequently:true});if(!ctx){bitmap.close();throw new Error("Не удалось проверить фотографию")};ctx.drawImage(bitmap,0,0,size,size);bitmap.close();const px=ctx.getImageData(0,0,size,size).data;let light=0;for(let i=0;i<px.length;i+=4)light+=(px[i]??0)*.299+(px[i+1]??0)*.587+(px[i+2]??0)*.114;light/=px.length/4;if(light<42)throw new Error("Фото слишком тёмное. Сфотографируйте заново при хорошем освещении");if(light>238)throw new Error("Фото пересвечено. Сфотографируйте заново без бликов");quality="accepted"}
 const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return{name:file.name,contentType:file.type,data:btoa(binary),quality};
}

export function LaboratoryManagement({locale:_locale}:{locale:Locale}){
 const[tab,setTab]=useState<"orders"|"catalog">("orders"),[orders,setOrders]=useState<Order[]>([]),[tests,setTests]=useState<Test[]>([]),[branches,setBranches]=useState<Branch[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[patients,setPatients]=useState<Patient[]>([]),[query,setQuery]=useState(""),[selectedPatient,setSelectedPatient]=useState<Patient|null>(null),[filter,setFilter]=useState(""),[showOrder,setShowOrder]=useState(false),[showTest,setShowTest]=useState(false),[editingTest,setEditingTest]=useState<Test|null>(null),[resultOrder,setResultOrder]=useState<Order|null>(null),[error,setError]=useState("");
 const load=async()=>{const[o,t,b,e]=await Promise.all([fetch(`/api/clinic/laboratory/orders${filter?`?status=${filter}`:""}`,{cache:"no-store"}),fetch("/api/clinic/laboratory/tests",{cache:"no-store"}),fetch("/api/clinic/branches",{cache:"no-store"}),fetch("/api/clinic/employees",{cache:"no-store"})]);if(o.ok)setOrders((await o.json()).items??[]);if(t.ok)setTests((await t.json()).items??[]);if(b.ok)setBranches((await b.json()).items??[]);if(e.ok)setEmployees((await e.json()).items??[])};
 useEffect(()=>{void load()},[filter]);useEffect(()=>{if(query.trim().length<2){setPatients([]);return}const timer=setTimeout(async()=>{const r=await fetch(`/api/clinic/patients?q=${encodeURIComponent(query)}`,{cache:"no-store"});if(r.ok)setPatients((await r.json()).items??[])},250);return()=>clearTimeout(timer)},[query]);
 const counts=useMemo(()=>Object.fromEntries(Object.keys(status).map(s=>[s,orders.filter(x=>x.status===s).length])),[orders]);
 const saveOrder=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selectedPatient){setError("Выберите пациента из найденного списка");return};const f=new FormData(e.currentTarget),testIds=f.getAll("testIds").map(String);if(!testIds.length){setError("Выберите хотя бы один анализ");return};const r=await fetch("/api/clinic/laboratory/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({patientId:selectedPatient.id,branchId:f.get("branchId"),employeeId:f.get("employeeId"),priority:f.get("priority"),clinicalNote:f.get("clinicalNote"),testIds})});if(!r.ok){setError("Не удалось создать направление. Проверьте поля");return};setShowOrder(false);setSelectedPatient(null);setQuery("");setError("");await load()};
 const saveTest=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch(editingTest?`/api/clinic/laboratory/tests/${editingTest.id}`:"/api/clinic/laboratory/tests",{method:editingTest?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:f.get("name"),code:f.get("code"),specimen:f.get("specimen"),description:f.get("description"),priceUzs:Number(f.get("priceUzs")||0),isActive:editingTest?.isActive??true})});if(!r.ok){setError("Не удалось сохранить вид анализа");return};setShowTest(false);setEditingTest(null);await load()};
 const changeStatus=async(o:Order,value:string)=>{const r=await fetch(`/api/clinic/laboratory/orders/${o.id}/status`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:value})});if(!r.ok)setError("Не удалось изменить статус");else await load()};
 const toggleTest=async(t:Test)=>{await fetch(`/api/clinic/laboratory/tests/${t.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...t,isActive:!t.isActive})});await load()};
 const saveResults=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!resultOrder)return;setError("");try{const f=new FormData(e.currentTarget),file=f.get("attachment");if(!(file instanceof File)||!file.size)throw new Error("Прикрепите файл результата");const body={resultNote:f.get("resultNote"),attachment:await attachment(file),items:resultOrder.items.map(x=>({itemId:x.id,result:f.get(`result-${x.id}`),unit:f.get(`unit-${x.id}`),referenceRange:f.get(`range-${x.id}`)}))};const r=await fetch(`/api/clinic/laboratory/orders/${resultOrder.id}/results`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error("Не удалось сохранить результаты");setResultOrder(null);await load()}catch(x){setError(x instanceof Error?x.message:"Не удалось сохранить результаты")}};
 return <section className="management laboratory"><div className="management-head"><div><p>ДИАГНОСТИКА</p><h1>Лаборатория</h1><span>Направления, приём материала и результаты анализов пациентов</span></div><button className="primary" onClick={()=>tab==="orders"?setShowOrder(true):(setEditingTest(null),setShowTest(true))}>+ {tab==="orders"?"Новое направление":"Добавить анализ"}</button></div>
 <div className="laboratory-tabs"><button className={tab==="orders"?"active":""} onClick={()=>setTab("orders")}>Направления</button><button className={tab==="catalog"?"active":""} onClick={()=>setTab("catalog")}>Виды анализов</button></div>{error&&<div className="management-error">{error}</div>}
 {tab==="orders"&&<><div className="lab-summary">{Object.entries(status).map(([id,name])=><button key={id} className={filter===id?"active":""} onClick={()=>setFilter(filter===id?"":id)}><b>{counts[id]??0}</b><span>{name}</span></button>)}</div>
 {showOrder&&<form className="admin-form lab-order-form" onSubmit={saveOrder}><label className="patient-picker">Пациент<input value={query} onChange={e=>{setQuery(e.target.value);setSelectedPatient(null)}} placeholder="Введите имя или фамилию" required/>{patients.length>0&&!selectedPatient&&<span className="patient-options">{patients.map(x=><button type="button" key={x.id} onClick={()=>{setSelectedPatient(x);setQuery(`${x.lastName} ${x.firstName} ${x.middleName??""}`);setPatients([])}}>{x.lastName} {x.firstName} {x.middleName}</button>)}</span>}</label><label>Филиал<select name="branchId" required><option value="">—</option>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Направивший врач<select name="employeeId"><option value="">—</option>{employees.filter(x=>x.isActive).map(x=><option key={x.id} value={x.id}>{x.lastName} {x.firstName}</option>)}</select></label><label>Срочность<select name="priority"><option value="ROUTINE">Планово</option><option value="URGENT">Срочно</option></select></label><fieldset className="lab-test-picker"><legend>Необходимые анализы</legend>{tests.filter(x=>x.isActive).map(x=><label key={x.id}><input type="checkbox" name="testIds" value={x.id}/><span><strong>{x.name}</strong><small>{x.specimen}{x.code?` · ${x.code}`:""}</small></span></label>)}</fieldset><label className="wide">Клиническая информация<textarea name="clinicalNote" rows={3} placeholder="Причина направления, симптомы, диагноз…"/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setShowOrder(false)}>Отмена</button><button className="primary">Создать направление</button></div></form>}
 <div className="lab-order-list">{orders.length===0?<div className="table-empty">Направлений пока нет</div>:orders.map(o=><article key={o.id} className={`${o.status.toLowerCase()} ${o.priority.toLowerCase()}`}><header><div><span className="lab-order-status">{status[o.status]??o.status}</span>{o.priority==="URGENT"&&<span className="urgent-label">Срочно</span>}<h2>{o.patient.name}</h2><p>{o.branch.name} · {new Date(o.createdAt).toLocaleString("ru-RU")}{o.employee.name?` · врач ${o.employee.name}`:""}</p></div><div className="lab-actions">{nextStatus[o.status]&&<button className="secondary" onClick={()=>void changeStatus(o,nextStatus[o.status]!)}>{status[nextStatus[o.status]!]}</button>}{(o.status==="SAMPLE_COLLECTED"||o.status==="IN_PROGRESS")&&<button className="primary" onClick={()=>setResultOrder(o)}>Внести результат</button>}{o.status!=="COMPLETED"&&o.status!=="CANCELLED"&&<button className="danger-button" onClick={()=>void changeStatus(o,"CANCELLED")}>Отменить</button>}{o.attachmentId&&<a className="secondary" target="_blank" href={`/api/clinic/lab-attachments/${o.attachmentId}`}>Открыть файл</a>}</div></header><div className="lab-order-tests">{o.items.map(x=><span key={x.id}><b>{x.name}</b>{x.result&&<small>{x.result} {x.unit}</small>}</span>)}</div>{o.clinicalNote&&<p className="lab-note">{o.clinicalNote}</p>}</article>)}</div></>}
 {tab==="catalog"&&<>{showTest&&<form className="admin-form" onSubmit={saveTest}><label>Название<input name="name" required defaultValue={editingTest?.name}/></label><label>Код<input name="code" defaultValue={editingTest?.code??""}/></label><label>Материал<input name="specimen" required defaultValue={editingTest?.specimen??"Кровь"}/></label><label>Описание<input name="description" defaultValue={editingTest?.description??""}/></label><label>Цена, сум<input name="priceUzs" type="number" min="0" step="1" required defaultValue={editingTest?.priceUzs??0}/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setShowTest(false)}>Отмена</button><button className="primary">Сохранить</button></div></form>}<div className="lab-catalog">{tests.map(t=><article key={t.id} className={!t.isActive?"disabled":""}><div><span>{t.code||"—"}</span><h2>{t.name}</h2><p>{t.specimen}{t.description?` · ${t.description}`:""} · {t.priceUzs?`${new Intl.NumberFormat("ru-RU").format(t.priceUzs)} сум`:"цена не задана"}</p></div><div><button className="secondary" onClick={()=>{setEditingTest(t);setShowTest(true)}}>Изменить</button><button className="secondary" onClick={()=>void toggleTest(t)}>{t.isActive?"Отключить":"Активировать"}</button></div></article>)}</div></>}
 {resultOrder&&<div className="lab-result-overlay"><form className="lab-result-form" onSubmit={saveResults}><header><div><span>РЕЗУЛЬТАТЫ АНАЛИЗОВ</span><h2>{resultOrder.patient.name}</h2></div><button type="button" onClick={()=>setResultOrder(null)}>×</button></header>{resultOrder.items.map(x=><div className="lab-result-row" key={x.id}><strong>{x.name}</strong><input name={`result-${x.id}`} required placeholder="Результат" defaultValue={x.result??""}/><input name={`unit-${x.id}`} placeholder="Единица" defaultValue={x.unit??""}/><input name={`range-${x.id}`} placeholder="Референс" defaultValue={x.referenceRange??""}/></div>)}<label>Заключение<textarea name="resultNote" rows={3}/></label><label className="analysis-file"><strong>Файл или фотография результата *</strong><input type="file" name="attachment" required accept="image/jpeg,image/png,image/webp,application/pdf"/><span>До 10 МБ. Фотография проверяется на размер и освещение.</span></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setResultOrder(null)}>Отмена</button><button className="primary">Подтвердить и сохранить в медкарте</button></div></form></div>}
 </section>
}
