"use client";
import {FormEvent,useEffect,useState} from "react";
import {Locale} from "@/lib/i18n";
type Item={id:string;senderName:string;recipientName:string;body:string;createdAt:string};
type Employee={userId:string;firstName:string;lastName:string;position:string};
export function MessageArchive({locale}:{locale:Locale}){
 const t=locale==="ru"?{k:"ТОЛЬКО ВЛАДЕЛЕЦ",h:"Архив чатов",s:"История внутренних сообщений · хранение минимум 3 месяца",employee:"Сотрудник",all:"Все сотрудники",from:"С даты",to:"По дату",search:"Показать",empty:"Сообщений за выбранный период нет",sender:"Отправитель",recipient:"Получатель"}:locale==="uz"?{k:"FAQAT EGASI",h:"Chat arxivi",s:"Ichki xabarlar tarixi · kamida 3 oy saqlanadi",employee:"Xodim",all:"Barcha xodimlar",from:"Boshlanish",to:"Tugash",search:"Ko‘rsatish",empty:"Tanlangan davrda xabarlar yo‘q",sender:"Yuboruvchi",recipient:"Qabul qiluvchi"}:{k:"OWNER ONLY",h:"Chat archive",s:"Internal message history · retained for at least 3 months",employee:"Employee",all:"All employees",from:"From",to:"To",search:"Show",empty:"No messages in this period",sender:"Sender",recipient:"Recipient"};
 const[items,setItems]=useState<Item[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async(query="")=>{setLoading(true);setError("");const r=await fetch(`/api/clinic/messages-archive${query}`,{cache:"no-store"});if(r.ok)setItems((await r.json()).items??[]);else setError(r.status===403?"Доступ разрешён только владельцу клиники":"Не удалось загрузить архив");setLoading(false)};
 useEffect(()=>{void load();void fetch("/api/clinic/employees",{cache:"no-store"}).then(async r=>{if(r.ok)setEmployees((await r.json()).items??[])})},[]);
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),q=new URLSearchParams();for(const key of["participant","from","to"]){const value=String(f.get(key)??"");if(value)q.set(key,value)}void load(`?${q}`)};
 return <section className="management"><div className="management-head"><div><p>{t.k}</p><h1>{t.h}</h1><span>{t.s}</span></div></div><form className="archive-filters" onSubmit={submit}><label className="archive-employee">{t.employee}<select name="participant"><option value="">{t.all}</option>{employees.map(x=><option key={x.userId} value={x.userId}>{x.lastName} {x.firstName} · {x.position}</option>)}</select></label><label>{t.from}<input type="date" name="from"/></label><label>{t.to}<input type="date" name="to"/></label><button className="primary">{t.search}</button></form>{error&&<div className="management-error">{error}</div>}<div className="archive-list">{loading?<div className="table-empty">…</div>:items.length===0?<div className="table-empty">{t.empty}</div>:items.map(x=><article key={x.id}><header><strong>{t.sender}: {x.senderName}</strong><span>→</span><strong>{t.recipient}: {x.recipientName}</strong><time>{new Date(x.createdAt).toLocaleString(locale)}</time></header><p>{x.body}</p></article>)}</div></section>
}
