/* eslint-disable @typescript-eslint/no-unused-expressions */
"use client";
import {useEffect,useRef,useState} from "react";
import {Locale} from "@/lib/i18n";
type Contact={id:string;name:string;unread:number};
type Appointment={id:string;status:string;patient:{name:string};employee:{name:string}};
type Toast={id:string;title:string;detail:string;target:"messages"|"appointments"};
export function MessageNotifier({locale,onOpen,onOpenAppointments,onUnreadChange}:{locale:Locale;onOpen:()=>void;onOpenAppointments:()=>void;onUnreadChange:(count:number)=>void}){
 const[toasts,setToasts]=useState<Toast[]>([]),previousMessages=useRef<Map<string,number>|null>(null),previousAppointments=useRef<Map<string,string>|null>(null),audioContext=useRef<AudioContext|null>(null);
 const copy=locale==="ru"?{message:"Новое сообщение",appointment:"Новая запись",status:"Статус приёма изменён"}:locale==="uz"?{message:"Yangi xabar",appointment:"Yangi qabul",status:"Qabul holati o‘zgardi"}:{message:"New message",appointment:"New appointment",status:"Appointment status changed"};
 const statusName=(value:string)=>({scheduled:"Запланирован",confirmed:"Подтверждён",arrived:"Пациент прибыл",in_progress:"Приём начат",completed:"Завершён",cancelled:"Отменён",no_show:"Не явился"}[value]||value);
 const playNotification=()=>{try{const AudioContextClass=window.AudioContext;const context=audioContext.current??new AudioContextClass();audioContext.current=context;if(context.state!=="running")return;const oscillator=context.createOscillator(),gain=context.createGain(),now=context.currentTime;oscillator.type="sine";oscillator.frequency.setValueAtTime(740,now);oscillator.frequency.setValueAtTime(880,now+.09);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.16,now+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+.24);oscillator.connect(gain);gain.connect(context.destination);oscillator.start(now);oscillator.stop(now+.25)}catch{/* Уведомление остаётся видимым, даже если браузер запретил звук. */}};
 useEffect(()=>{const unlock=()=>{try{const AudioContextClass=window.AudioContext;const context=audioContext.current??new AudioContextClass();audioContext.current=context;if(context.state==="suspended")void context.resume()}catch{/* Визуальные уведомления продолжат работать. */}};window.addEventListener("pointerdown",unlock,{once:true});window.addEventListener("keydown",unlock,{once:true});return()=>{window.removeEventListener("pointerdown",unlock);window.removeEventListener("keydown",unlock)}},[]);
 useEffect(()=>{let active=true;const check=async()=>{const r=await fetch("/api/clinic/messages/contacts",{cache:"no-store"});if(!r.ok||!active)return;const contacts=((await r.json()).items??[])as Contact[],next=new Map(contacts.map(x=>[x.id,x.unread]));onUnreadChange(contacts.reduce((sum,x)=>sum+x.unread,0));if(previousMessages.current){const incoming=contacts.filter(x=>x.unread>(previousMessages.current?.get(x.id)??0));if(incoming.length){playNotification();setToasts(current=>[...current,...incoming.map(x=>({id:`message-${x.id}-${Date.now()}`,title:copy.message,detail:x.name,target:"messages" as const}))].slice(-4))}}previousMessages.current=next};void check();const timer=window.setInterval(()=>void check(),1200);return()=>{active=false;window.clearInterval(timer)}},[copy.message,onUnreadChange]);
 useEffect(()=>{let active=true;const check=async()=>{const r=await fetch("/api/clinic/appointments?scope=active",{cache:"no-store"});if(!r.ok||!active)return;const appointments=((await r.json()).items??[])as Appointment[],next=new Map(appointments.map(x=>[x.id,x.status]));if(previousAppointments.current){const notices:Toast[]=[];for(const item of appointments){const old=previousAppointments.current.get(item.id);if(!old)notices.push({id:`appointment-${item.id}-${Date.now()}`,title:copy.appointment,detail:`${item.patient.name} · ${item.employee.name}`,target:"appointments"});else if(old!==item.status)notices.push({id:`status-${item.id}-${Date.now()}`,title:copy.status,detail:`${item.patient.name} · ${statusName(item.status)}`,target:"appointments"})}if(notices.length)setToasts(current=>[...current,...notices].slice(-4))}previousAppointments.current=next};void check();const timer=window.setInterval(()=>void check(),2000);return()=>{active=false;window.clearInterval(timer)}},[copy.appointment,copy.status]);
 useEffect(()=>{if(!toasts.length)return;const timer=window.setTimeout(()=>setToasts(current=>current.slice(1)),6500);return()=>window.clearTimeout(timer)},[toasts]);
 return <div className="message-toasts" aria-live="polite">{toasts.map(x=><button key={x.id} onClick={()=>{setToasts([]);x.target==="messages"?onOpen():onOpenAppointments()}}><span>{x.target==="messages"?"✉":"▣"}</span><div><strong>{x.title}</strong><p>{x.detail}</p></div><i aria-hidden="true">×</i></button>)}</div>
}
