"use client";
import {FormEvent,useCallback,useEffect,useRef,useState} from "react";
import {Locale} from "@/lib/i18n";
type Contact={id:string;name:string;position:string;specialty?:string|null;branch?:string|null;isActive:boolean;unread:number};type Message={id:string;body:string;createdAt:string;mine:boolean};
export function MessageCenter({locale}:{locale:Locale}){
 const tx={ru:["СООБЩЕНИЯ","Внутренний чат","Безопасное общение сотрудников клиники","Сотрудники","Выберите сотрудника","Сообщений пока нет","Напишите сообщение…","Отправить"],uz:["XABARLAR","Ichki chat","Klinika xodimlarining xavfsiz muloqoti","Xodimlar","Xodimni tanlang","Xabarlar yo‘q","Xabar yozing…","Yuborish"],en:["MESSAGES","Internal chat","Secure clinic staff communication","Employees","Select an employee","No messages yet","Write a message…","Send"]}[locale];
 const[contacts,setContacts]=useState<Contact[]>([]),[selected,setSelected]=useState<Contact|null>(null),[chatMessages,setChatMessages]=useState<Message[]>([]),[sending,setSending]=useState(false);const thread=useRef<HTMLDivElement>(null),previousCount=useRef(0);
 const loadContacts=useCallback(async()=>{const r=await fetch("/api/clinic/messages/contacts",{cache:"no-store"});if(r.ok)setContacts((await r.json()).items??[])},[]);
 const loadMessages=useCallback(async(id:string)=>{const r=await fetch(`/api/clinic/messages/${id}`,{cache:"no-store"});if(r.ok)setChatMessages((await r.json()).items??[])},[]);
 useEffect(()=>{void loadContacts();const x=window.setInterval(()=>void loadContacts(),1500);return()=>window.clearInterval(x)},[loadContacts]);
 useEffect(()=>{if(!selected)return;previousCount.current=0;setChatMessages([]);void loadMessages(selected.id);const x=window.setInterval(()=>void loadMessages(selected.id),1000);return()=>window.clearInterval(x)},[selected,loadMessages]);
 useEffect(()=>{const box=thread.current;if(!box)return;const firstLoad=previousCount.current===0&&chatMessages.length>0,nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<130;if(firstLoad||nearBottom)box.scrollTop=box.scrollHeight;previousCount.current=chatMessages.length},[chatMessages]);
 const send=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected||sending)return;const form=e.currentTarget,body=String(new FormData(form).get("body")??"").trim();if(!body)return;setSending(true);const r=await fetch(`/api/clinic/messages/${selected.id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body})});if(r.ok){const created=await r.json() as Message;setChatMessages(current=>current.some(x=>x.id===created.id)?current:[...current,created]);form.reset();requestAnimationFrame(()=>{if(thread.current)thread.current.scrollTop=thread.current.scrollHeight})}setSending(false)};
 return <section className="management"><div className="management-head"><div><p>{tx[0]}</p><h1>{tx[1]}</h1><span>{tx[2]}</span></div></div><div className="messenger"><aside><h2>{tx[3]}</h2><div className="message-contacts">{contacts.map(x=><button key={x.id} className={selected?.id===x.id?"active":""} onClick={()=>setSelected(x)}><i className={x.isActive?"online":""}/><span><strong>{x.name}</strong><small>{x.specialty||x.position}{x.branch?` · ${x.branch}`:""}</small></span>{x.unread>0&&<b>{x.unread}</b>}</button>)}</div></aside><main>{!selected?<div className="message-empty">{tx[4]}</div>:<><header className="chat-peer"><strong>{selected.name}</strong><span>{selected.specialty||selected.position}{selected.branch?` · ${selected.branch}`:""}</span></header><div className="message-thread" ref={thread}>{chatMessages.length===0?<div className="message-empty">{tx[5]}</div>:chatMessages.map(x=><article key={x.id} className={x.mine?"mine":"theirs"}><p>{x.body}</p><time>{new Date(x.createdAt).toLocaleTimeString(locale,{hour:"2-digit",minute:"2-digit"})}</time></article>)}</div><form onSubmit={send}><input name="body" maxLength={4000} autoComplete="off" placeholder={tx[6]}/><button disabled={sending}>{tx[7]}</button></form></>}</main></div></section>
}
