"use client";

import Image from "next/image";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { CSSProperties } from "react";

type Call={id:string;number:string;status:string;room:string;doctor:string;specialty:string;patient:string;calledAt:string};
type Media={id:string;kind:string;title:string;assetKey?:string;language?:string;contentType:string;durationSeconds?:number};
type Settings=Record<string,string|number|boolean|undefined>;
type State={name:string;language:"ru"|"uz"|"en";voiceLanguage:string;settings:Settings;calls:Call[];tickers:string[];media:Media[]};
const words={
  ru:{current:"Текущий номер",room:"Кабинет",recent:"Последние вызовы",wait:"Ожидайте вызова",activate:"Включить экран и звук",hint:"Нажмите один раз после включения телевизора",offline:"Нет связи. Переподключение…",contact:"Связаться с нами",announcement:"Объявление"},
  uz:{current:"Hozirgi navbat",room:"Xona",recent:"So‘nggi chaqiruvlar",wait:"Chaqiruvni kuting",activate:"Ekran va ovozni yoqish",hint:"Televizorni yoqqandan so‘ng bir marta bosing",offline:"Aloqa yo‘q. Qayta ulanmoqda…",contact:"Biz bilan bog‘laning",announcement:"E’lon"},
  en:{current:"Current queue",room:"Room",recent:"Recent calls",wait:"Please wait to be called",activate:"Enable display and sound",hint:"Click once after turning on the TV",offline:"Connection lost. Reconnecting…",contact:"Contact us",announcement:"Announcement"}
};

export function QueueTVDisplay({token}:{token:string}){
  const [state,setState]=useState<State|null>(null),[enabled,setEnabled]=useState(false),[online,setOnline]=useState(false),[now,setNow]=useState(new Date()),[mediaIndex,setMediaIndex]=useState(0);
  const audioChain=useRef<Promise<void>>(Promise.resolve()),lastAnnounced=useRef("");
  const load=useCallback(async()=>{const response=await fetch(`/api/display/${encodeURIComponent(token)}`,{cache:"no-store"});if(response.ok){setState(await response.json());setOnline(true)}else setOnline(false)},[token]);
  useEffect(()=>{void load();const source=new EventSource(`/api/display/${encodeURIComponent(token)}/events`);source.onopen=()=>setOnline(true);source.onerror=()=>setOnline(false);source.addEventListener("queue",event=>{const data=JSON.parse((event as MessageEvent).data);const entry=data.entry as Call;void load();if(entry?.id&&entry.id!==lastAnnounced.current){lastAnnounced.current=entry.id;announce(entry)}});const poll=window.setInterval(()=>void load(),15000);return()=>{source.close();window.clearInterval(poll)}},[load]);
  useEffect(()=>{const timer=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(timer)},[]);
  const visualMedia=useMemo(()=>state?.media?.filter(item=>["VIDEO","BANNER","IMAGE"].includes(item.kind))??[],[state]);
  useEffect(()=>{if(visualMedia.length<2)return;const seconds=visualMedia[mediaIndex]?.durationSeconds??12;const timer=window.setTimeout(()=>setMediaIndex(value=>(value+1)%visualMedia.length),seconds*1000);return()=>window.clearTimeout(timer)},[mediaIndex,visualMedia]);
  const play=(asset:Media)=>new Promise<void>(resolve=>{const audio=new Audio(`/api/display/${encodeURIComponent(token)}/media/${asset.id}`);audio.onended=()=>resolve();audio.onerror=()=>resolve();void audio.play().catch(()=>resolve())});
  const announce=(entry:Call)=>{if(!enabled||!state)return;const assets=state.media??[];const language=state.voiceLanguage||state.language;const select=(key:string)=>assets.find(item=>["AUDIO","NOTIFICATION"].includes(item.kind)&&item.assetKey===key&&(!item.language||item.language===language));const sequence:Media[]=[];const notification=select("notification");if(notification)sequence.push(notification);const number=select("number_word");if(number)sequence.push(number);for(const digit of entry.number.replace(/\D/g,"")){const part=select(`digit_${digit}`);if(part)sequence.push(part)}const please=select("please_go");if(please)sequence.push(please);const room=select("room_word");if(room)sequence.push(room);for(const digit of entry.room.replace(/\D/g,"")){const part=select(`digit_${digit}`);if(part)sequence.push(part)}audioChain.current=audioChain.current.then(async()=>{for(const asset of sequence)await play(asset)})};
  const activate=async()=>{setEnabled(true);const notification=state?.media?.find(item=>item.assetKey==="notification");if(notification)await play(notification);document.documentElement.requestFullscreen?.().catch(()=>undefined)};
  if(!state)return <main className="tv-loading"><Image src="/brand-mark.png" alt="" width={90} height={90}/><strong>ONA VA BOLA KLINIKASI</strong><span>{online?"Загрузка…":"Подключение…"}</span></main>;
  const language=state.language,t=words[language],settings=state.settings??{},current=state.calls?.[0],recent=state.calls?.slice(1,Number(settings.recentCallCount??7))??[],currentMedia=visualMedia[mediaIndex%Math.max(visualMedia.length,1)];
  const locale=language==="uz"?"uz-UZ":language;
  const qr=state.media.find(item=>item.kind==="QR"&&item.id===settings.qrMediaId);
  const ticker=state.tickers?.length?state.tickers.join("   •   "):language==="uz"?"Klinikamiz har kuni 08:00 dan 20:00 gacha ishlaydi   •   Navbatga o‘z vaqtida keling":"Клиника работает ежедневно с 08:00 до 20:00   •   Приходите к назначенному времени";
  return <main className="queue-tv queue-tv-modern" style={{"--tv-primary":settings.primaryColor||"#e80d4f","--tv-deep":settings.secondaryColor||"#8f0735","--tv-bg":settings.backgroundColor||"#fff7fa","--tv-text":settings.textColor||"#17202a"} as CSSProperties}>
    {!enabled&&<button className="tv-activate" onClick={()=>void activate()}><Image src="/brand-mark.png" alt="" width={88} height={88}/><strong>{t.activate}</strong><span>{t.hint}</span></button>}
    {!online&&<div className="tv-offline">{t.offline}</div>}
    <header className="tv-modern-header"><div className="tv-brand"><Image src="/brand-mark.png" alt="" width={78} height={78}/><div><b>ONA VA BOLA</b><span>KLINIKASI</span></div></div>{settings.showSlogan!==false&&<div className="tv-slogan"><strong>{String(settings.slogan||"SIZNING SOG‘LIG‘INGIZ — BIZNING G‘AMXO‘RLIGIMIZ")}</strong></div>}<div className="tv-date-time"><div><b>{now.toLocaleTimeString(locale,{hour:"2-digit",minute:"2-digit"})}</b><small>{now.toLocaleDateString(locale,{day:"2-digit",month:"2-digit",year:"numeric"})}</small></div><span/><div><strong>{now.toLocaleDateString(locale,{day:"numeric",month:"long",year:"numeric"})}</strong><small>{now.toLocaleDateString(locale,{weekday:"long"})}</small></div></div></header>
    <section className="tv-modern-grid"><article className="tv-call-card"><h1>{t.current}</h1>{current?<><strong className="tv-hero-number">{current.number}</strong><div className="tv-sound-line"><span/><b>♪</b><span/></div><h2>{current.room?`${current.room}-${t.room.toUpperCase()}`:t.wait}</h2>{settings.showSpecialty!==false&&<p>{current.specialty||current.doctor}</p>}</>:<div className="tv-modern-empty"><strong>—</strong><span>{t.wait}</span></div>}</article>
      <article className="tv-hero-media">{currentMedia?(currentMedia.kind==="VIDEO"?<video key={currentMedia.id} src={`/api/display/${encodeURIComponent(token)}/media/${currentMedia.id}`} autoPlay muted loop playsInline/>:<img src={`/api/display/${encodeURIComponent(token)}/media/${currentMedia.id}`} alt={currentMedia.title}/>):<Image src="/queue-clinic-default.png" alt="Интерьер клиники" fill priority sizes="45vw"/>}<div className="tv-hero-copy"><strong>{String(settings.heroTitle||"Современная клиника")}</strong><span>{String(settings.heroSubtitle||"Лучшие условия для вас")}</span></div>{visualMedia.length>1&&<div className="tv-media-dots">{visualMedia.map((item,index)=><i key={item.id} className={index===mediaIndex?"active":""}/>)}</div>}</article>
      <article className="tv-recent-card"><h2>{t.recent}</h2><div>{recent.length?recent.map(call=><section key={call.id}><b>{call.number}</b><strong>{call.room?`${call.room}-${t.room.toUpperCase()}`:"—"}</strong><time>{call.calledAt?new Date(call.calledAt).toLocaleTimeString(locale,{hour:"2-digit",minute:"2-digit"}):""}</time></section>):<p>{t.wait}</p>}</div></article></section>
    {((settings.showPhone!==false&&settings.phone)||(settings.showInstagram!==false&&settings.instagram)||(settings.showTelegram!==false&&settings.telegram)||(settings.showQr!==false&&qr))&&<section className="tv-contact-bar">{settings.showPhone!==false&&settings.phone&&<div><small>{t.contact}</small><strong>{String(settings.phone)}</strong></div>}{settings.showInstagram!==false&&settings.instagram&&<div><small>Instagram</small><strong>{String(settings.instagram)}</strong></div>}{settings.showTelegram!==false&&settings.telegram&&<div><small>Telegram</small><strong>{String(settings.telegram)}</strong></div>}{settings.showQr!==false&&qr&&<img src={`/api/display/${encodeURIComponent(token)}/media/${qr.id}`} alt="QR-код клиники"/>}</section>}
    {settings.showTicker!==false&&<footer className="tv-modern-ticker"><b>{t.announcement}:</b><div><span>{ticker}</span></div></footer>}
  </main>;
}
