"use client";
import { FormEvent, useEffect, useState } from "react";
import { Locale } from "@/lib/i18n";

type Branch={id:string;name:string};
type Employee={id:string;firstName:string;lastName:string;branchId?:string|null;position:string;specialty?:string|null;isActive:boolean};
type Price={branchId:string;branch:string;employeeId?:string|null;employee?:string;amountUzs:number};
type Provider={branchId:string;employeeId:string;employee:string};
type ServiceSpecialty={branchId:string;specialty:string};
type Service={id:string;code:string;name:string;description:string;category:string;durationMinutes:number;isActive:boolean;prices:Price[];providers:Provider[];specialties:ServiceSpecialty[]};
const money=(value:number)=>new Intl.NumberFormat("ru-RU").format(value)+" сум";

export function ServiceManagement({locale}:{locale:Locale}){
 const t=locale==="ru"?{k:"СПРАВОЧНИК",h:"Услуги и цены",s:"Цены по филиалам и индивидуальные цены врачей",add:"Добавить услугу",category:"Категория",name:"Название услуги",code:"Код",description:"Описание",duration:"Длительность (мин)",save:"Сохранить",cancel:"Отмена",edit:"Изменить",disable:"Отключить",price:"Настроить цену",branch:"Филиал",doctor:"Врач (необязательно)",base:"Общая цена филиала",amount:"Цена, сум",empty:"Услуги пока не добавлены",noPrice:"Цена ещё не назначена",active:"Активна",inactive:"Отключена",error:"Не удалось сохранить данные"}:locale==="uz"?{k:"MA’LUMOTNOMA",h:"Xizmatlar va narxlar",s:"Filiallar va shifokorlar bo‘yicha narxlar",add:"Xizmat qo‘shish",category:"Toifa",name:"Xizmat nomi",code:"Kod",description:"Tavsif",duration:"Davomiyligi (daq)",save:"Saqlash",cancel:"Bekor qilish",edit:"Tahrirlash",disable:"O‘chirish",price:"Narxni sozlash",branch:"Filial",doctor:"Shifokor (ixtiyoriy)",base:"Filialning umumiy narxi",amount:"Narx, so‘m",empty:"Xizmatlar yo‘q",noPrice:"Narx belgilanmagan",active:"Faol",inactive:"O‘chirilgan",error:"Ma’lumotni saqlab bo‘lmadi"}:{k:"CATALOG",h:"Services and prices",s:"Branch prices and individual doctor prices",add:"Add service",category:"Category",name:"Service name",code:"Code",description:"Description",duration:"Duration (min)",save:"Save",cancel:"Cancel",edit:"Edit",disable:"Disable",price:"Set price",branch:"Branch",doctor:"Doctor (optional)",base:"Branch default price",amount:"Price, UZS",empty:"No services yet",noPrice:"No price assigned",active:"Active",inactive:"Disabled",error:"Could not save data"};
 const[items,setItems]=useState<Service[]>([]),[branches,setBranches]=useState<Branch[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[showForm,setShowForm]=useState(false),[editing,setEditing]=useState<Service|null>(null),[pricing,setPricing]=useState<Service|null>(null),[priceBranchId,setPriceBranchId]=useState(""),[basePrice,setBasePrice]=useState(""),[selectedSpecialties,setSelectedSpecialties]=useState<string[]>([]),[selectedDoctors,setSelectedDoctors]=useState<string[]>([]),[doctorPrices,setDoctorPrices]=useState<Record<string,string>>({}),[error,setError]=useState("");
 const load=async()=>{const[services,branchData,employeeData]=await Promise.all([fetch("/api/clinic/services",{cache:"no-store"}),fetch("/api/clinic/branches",{cache:"no-store"}),fetch("/api/clinic/employees",{cache:"no-store"})]);if(services.ok)setItems((await services.json()).items??[]);if(branchData.ok)setBranches((await branchData.json()).items??[]);if(employeeData.ok)setEmployees((await employeeData.json()).items??[])};
 useEffect(()=>{void load()},[]);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError("");const f=new FormData(e.currentTarget),body={category:f.get("category"),name:f.get("name"),code:f.get("code"),description:f.get("description"),durationMinutes:Number(f.get("duration")),isActive:true};const r=await fetch(editing?`/api/clinic/services/${editing.id}`:"/api/clinic/services",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError(t.error);return}setShowForm(false);setEditing(null);await load()};
 const configureBranch=(service:Service,branchId:string)=>{setPriceBranchId(branchId);const base=service.prices.find(x=>x.branchId===branchId&&!x.employeeId);setBasePrice(base?String(base.amountUzs):"");setSelectedSpecialties(service.specialties.filter(x=>x.branchId===branchId).map(x=>x.specialty));const providerIds=service.providers.filter(x=>x.branchId===branchId).map(x=>x.employeeId);setSelectedDoctors(providerIds);const values:Record<string,string>={};for(const price of service.prices.filter(x=>x.branchId===branchId&&x.employeeId))values[price.employeeId!]=String(price.amountUzs);setDoctorPrices(values)};
 const toggleSpecialty=(specialty:string,checked:boolean)=>{setSelectedSpecialties(current=>checked?[...current,specialty]:current.filter(x=>x!==specialty));const doctorIds=employees.filter(x=>x.isActive&&x.branchId===priceBranchId&&x.specialty===specialty).map(x=>x.id);setSelectedDoctors(current=>checked?Array.from(new Set([...current,...doctorIds])):current.filter(id=>!doctorIds.includes(id)||Boolean(doctorPrices[id]?.trim())))};
 const savePrice=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!pricing)return;setError("");const providers=selectedDoctors.map(employeeId=>({employeeId,amountUzs:doctorPrices[employeeId]?.trim()?Number(doctorPrices[employeeId]):null}));const r=await fetch(`/api/clinic/services/${pricing.id}/providers`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({branchId:priceBranchId,baseAmountUzs:Number(basePrice),specialties:selectedSpecialties,providers})});if(!r.ok){const data=await r.json().catch(()=>null),code=data?.error?.code;setError(code==="employee_branch_mismatch"?(locale==="ru"?"Один из выбранных врачей не работает в этом филиале":locale==="uz"?"Tanlangan shifokorlardan biri bu filialda ishlamaydi":"One selected doctor does not work at this branch"):code==="invalid_specialty"?(locale==="ru"?"В выбранном филиале нет активных врачей этой специальности":"This specialty is unavailable at the branch"):t.error);return}setPricing(null);await load()};
 const disable=async(x:Service)=>{if(!window.confirm(`${t.disable}: ${x.name}?`))return;await fetch(`/api/clinic/services/${x.id}`,{method:"DELETE"});await load()};
 const openEdit=(x:Service)=>{setEditing(x);setShowForm(true);setPricing(null)};
 return <section className="management service-management"><div className="management-head"><div><p>{t.k}</p><h1>{t.h}</h1><span>{t.s}</span></div><button className="primary" onClick={()=>{setEditing(null);setShowForm(true);setPricing(null)}}>+ {t.add}</button></div>{error&&<div className="management-error">{error}</div>}
 {showForm&&<form className="service-form" onSubmit={submit}><label>{t.category}<input name="category" required minLength={2} defaultValue={editing?.category}/></label><label>{t.name}<input name="name" required minLength={2} defaultValue={editing?.name}/></label><label>{t.code}<input name="code" defaultValue={editing?.code}/></label><label>{t.duration}<input name="duration" type="number" min={5} max={1440} required defaultValue={editing?.durationMinutes??30}/></label><label className="service-description">{t.description}<input name="description" defaultValue={editing?.description}/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>{setShowForm(false);setEditing(null)}}>{t.cancel}</button><button className="primary">{t.save}</button></div></form>}
 {pricing&&<form className="service-price-form service-provider-form" onSubmit={savePrice}><h3>{t.price}: {pricing.name}</h3><label>{t.branch}<select required value={priceBranchId} onChange={e=>configureBranch(pricing,e.target.value)}><option value="" disabled>—</option>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>{t.base}<input value={basePrice} onChange={e=>setBasePrice(e.target.value)} type="number" min={0} step={1000} required placeholder="85000"/></label><fieldset className="specialty-picker"><legend>{locale==="ru"?"Назначить по специальности":locale==="uz"?"Mutaxassislik bo‘yicha tayinlash":"Assign by specialty"}</legend>{Array.from(new Set(employees.filter(x=>x.isActive&&x.branchId===priceBranchId&&x.specialty).map(x=>x.specialty!))).map(s=><label key={s}><input type="checkbox" checked={selectedSpecialties.includes(s)} onChange={e=>toggleSpecialty(s,e.target.checked)}/><span>{s}</span></label>)}</fieldset><fieldset className="provider-picker"><legend>{locale==="ru"?"Врачи и индивидуальные цены":locale==="uz"?"Shifokorlar va individual narxlar":"Doctors and individual prices"}</legend>{employees.filter(x=>x.isActive&&x.branchId===priceBranchId).map(x=>{const checked=selectedDoctors.includes(x.id);return <div key={x.id} className={checked?"selected":""}><label><input type="checkbox" checked={checked} onChange={e=>setSelectedDoctors(current=>e.target.checked?Array.from(new Set([...current,x.id])):current.filter(id=>id!==x.id))}/><span><strong>{x.lastName} {x.firstName}</strong><small>{x.specialty||x.position}{selectedSpecialties.includes(x.specialty||"")?" · по специальности":""}</small></span></label><input aria-label="Индивидуальная цена" type="number" min={0} step={1000} disabled={!checked} value={doctorPrices[x.id]??""} onChange={e=>setDoctorPrices(current=>({...current,[x.id]:e.target.value}))} placeholder={locale==="ru"?"Своя цена (необязательно)":"Optional price"}/></div>})}{employees.filter(x=>x.isActive&&x.branchId===priceBranchId).length===0&&<p>{locale==="ru"?"В этом филиале пока нет сотрудников":"No employees in this branch"}</p>}</fieldset><div className="form-actions"><button type="button" className="secondary" onClick={()=>setPricing(null)}>{t.cancel}</button><button className="primary">{t.save}</button></div></form>}
 <div className="service-list">{items.length===0?<div className="table-empty">{t.empty}</div>:items.map(x=><article key={x.id} className={!x.isActive?"disabled":""}><div className="service-main"><span>{x.category}</span><h2>{x.name}</h2><p>{x.description||"—"}</p><small>{x.code&&`${x.code} · `}{x.durationMinutes} мин · {x.isActive?t.active:t.inactive}</small></div><div className="service-prices">{x.prices.length===0?<p>{t.noPrice}</p>:x.prices.map((p,i)=><div key={`${p.branchId}-${p.employeeId??i}`}><strong>{money(p.amountUzs)}</strong><span>{p.branch}{p.employee?` · ${p.employee}`:""}</span></div>)}</div><div className="service-actions"><button className="secondary" onClick={()=>{setPricing(x);configureBranch(x,branches[0]?.id??"");setShowForm(false);setError("")}}>{t.price}</button><button className="secondary" onClick={()=>openEdit(x)}>{t.edit}</button>{x.isActive&&<button className="danger-button" onClick={()=>void disable(x)}>{t.disable}</button>}</div></article>)}</div></section>
}
