"use client";
import {FormEvent,useEffect,useState} from "react";
import {Locale} from "@/lib/i18n";
type Specialty={id:string;name:string;isActive:boolean;employeeCount:number;serviceCount:number};
type Employee={id:string;firstName:string;lastName:string;specialty?:string|null;position:string;branch?:string|null;isActive:boolean};
export function SpecialistManagement({locale,onServices}:{locale:Locale;onServices:()=>void}){
 const t=locale==="ru"?{k:"МЕДИЦИНСКИЙ СОСТАВ",h:"Специалисты",s:"Специальности, врачи и связанные услуги",add:"Добавить специальность",name:"Название специальности",save:"Сохранить",cancel:"Отмена",edit:"Изменить",remove:"Удалить",enable:"Активировать",disable:"Отключить",active:"Активна",inactive:"Неактивна",doctors:"врачей",services:"услуг",empty:"Специальности пока не созданы",inUse:"Нельзя удалить: сначала переведите сотрудников в другую специальность",error:"Не удалось сохранить изменения",open:"Настроить услуги"}:locale==="uz"?{k:"TIBBIY JAMOA",h:"Mutaxassislar",s:"Mutaxassisliklar, shifokorlar va xizmatlar",add:"Mutaxassislik qo‘shish",name:"Mutaxassislik nomi",save:"Saqlash",cancel:"Bekor qilish",edit:"Tahrirlash",remove:"O‘chirish",enable:"Faollashtirish",disable:"O‘chirish",active:"Faol",inactive:"Nofaol",doctors:"shifokor",services:"xizmat",empty:"Mutaxassisliklar yo‘q",inUse:"Avval xodimlarni boshqa mutaxassislikka o‘tkazing",error:"Saqlab bo‘lmadi",open:"Xizmatlarni sozlash"}:{k:"MEDICAL TEAM",h:"Specialists",s:"Specialties, doctors and linked services",add:"Add specialty",name:"Specialty name",save:"Save",cancel:"Cancel",edit:"Edit",remove:"Delete",enable:"Activate",disable:"Disable",active:"Active",inactive:"Inactive",doctors:"doctors",services:"services",empty:"No specialties yet",inUse:"Move linked employees before deleting",error:"Could not save changes",open:"Configure services"};
 const[items,setItems]=useState<Specialty[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[editing,setEditing]=useState<Specialty|null>(null),[show,setShow]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState<"all"|"active"|"inactive">("all");
 const load=async()=>{const[a,b]=await Promise.all([fetch("/api/clinic/specialists",{cache:"no-store"}),fetch("/api/clinic/employees",{cache:"no-store"})]);if(a.ok)setItems((await a.json()).items??[]);if(b.ok)setEmployees((await b.json()).items??[])};useEffect(()=>{void load()},[]);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch(editing?`/api/clinic/specialists/${editing.id}`:"/api/clinic/specialists",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:f.get("name"),isActive:editing?.isActive??true})});if(!r.ok){setError(t.error);return}setShow(false);setEditing(null);setError("");await load()};
 const toggle=async(x:Specialty)=>{const r=await fetch(`/api/clinic/specialists/${x.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:x.name,isActive:!x.isActive})});if(!r.ok){setError(t.error);return}await load()};
 const remove=async(x:Specialty)=>{if(!confirm(`${t.remove}: ${x.name}?`))return;const r=await fetch(`/api/clinic/specialists/${x.id}`,{method:"DELETE"});if(!r.ok){const data=await r.json().catch(()=>null);setError(data?.error?.code==="specialty_in_use"?t.inUse:t.error);return}await load()};
 const normalized=query.trim().toLowerCase();const filtered=items.filter(x=>{if(status==="active"&&!x.isActive||status==="inactive"&&x.isActive)return false;if(!normalized)return true;const doctorMatch=employees.some(e=>e.specialty?.toLowerCase()===x.name.toLowerCase()&&`${e.lastName} ${e.firstName}`.toLowerCase().includes(normalized));return x.name.toLowerCase().includes(normalized)||doctorMatch});
 return <section className="management specialist-management"><div className="management-head"><div><p>{t.k}</p><h1>{t.h}</h1><span>{t.s}</span></div><button className="primary" onClick={()=>{setEditing(null);setShow(true);setError("")}}>+ {t.add}</button></div><div className="specialist-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={locale==="ru"?"Поиск специальности или врача…":locale==="uz"?"Mutaxassislik yoki shifokorni qidirish…":"Search specialty or doctor…"}/><select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">{locale==="ru"?"Все специальности":locale==="uz"?"Barcha mutaxassisliklar":"All specialties"}</option><option value="active">{t.active}</option><option value="inactive">{t.inactive}</option></select><span>{filtered.length}</span></div>{error&&<div className="management-error">{error}</div>}{show&&<form className="specialist-form" onSubmit={submit}><label>{t.name}<input name="name" required minLength={2} defaultValue={editing?.name}/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setShow(false)}>{t.cancel}</button><button className="primary">{t.save}</button></div></form>}<div className="specialty-grid">{filtered.length===0?<div className="table-empty">{normalized?(locale==="ru"?"Ничего не найдено":"Nothing found"):t.empty}</div>:filtered.map(x=>{const doctors=employees.filter(e=>e.isActive&&e.specialty?.toLowerCase()===x.name.toLowerCase());return <article key={x.id} className={!x.isActive?"specialty-disabled":""}><header><div><span>{x.employeeCount} {t.doctors} · {x.serviceCount} {t.services} · {x.isActive?t.active:t.inactive}</span><h2>{x.name}</h2></div><div>{x.isActive&&<button className="secondary" onClick={onServices}>{t.open}</button>}<button className="secondary" onClick={()=>void toggle(x)}>{x.isActive?t.disable:t.enable}</button><button className="secondary" onClick={()=>{setEditing(x);setShow(true);setError("")}}>{t.edit}</button><button className="danger-button" onClick={()=>void remove(x)}>{t.remove}</button></div></header><div className="specialist-doctors">{doctors.map(d=><div key={d.id}><strong>{d.lastName} {d.firstName}</strong><span>{d.position}{d.branch?` · ${d.branch}`:""}</span></div>)}{doctors.length===0&&<small>—</small>}</div></article>})}</div></section>
}
