package app

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"regexp"
	"strconv"
	"strings"
	"time"

	"clinicos/api/internal/auth"
	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
)

var queueSlugPattern = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{1,48}$`)

func tokenHash(v string) string { x:=sha256.Sum256([]byte(v)); return hex.EncodeToString(x[:]) }
func newDisplayToken() string { b:=make([]byte,32); _,_=rand.Read(b); return hex.EncodeToString(b) }
func queueChannel(displayID string) string { return "queue:display:"+displayID }

func (a *App) listQueueEntries(w http.ResponseWriter,r *http.Request){
	p:=auth.PrincipalFrom(r.Context());branch:=r.URL.Query().Get("branchId")
	rows,e:=a.db.Query(r.Context(),`SELECT q.id,q.display_number,q.status,q.priority,q.created_at,q.called_at,p.id,concat_ws(' ',p.last_name,p.first_name,p.middle_name),e.id,concat_ws(' ',e.last_name,e.first_name),e.specialty,rm.id,rm.room_number,b.id,b.name,a.id,a.starts_at FROM queue_entries q JOIN patients p ON p.id=q.patient_id LEFT JOIN employees e ON e.id=q.employee_id LEFT JOIN queue_rooms rm ON rm.id=q.room_id JOIN branches b ON b.id=q.branch_id LEFT JOIN appointments a ON a.id=q.appointment_id WHERE q.organization_id=$1 AND q.queue_date=(now() AT TIME ZONE 'Asia/Tashkent')::date AND ($2='' OR q.branch_id::text=$2) ORDER BY CASE q.status WHEN 'CALLED' THEN 0 WHEN 'RECALLED' THEN 0 WHEN 'IN_SERVICE' THEN 1 WHEN 'WAITING' THEN 2 ELSE 3 END,q.priority DESC,q.sequence_number`,p.OrganizationID,branch)
	if e!=nil{errorJSON(w,500,"database_error","Could not load queue",requestID(r));return};defer rows.Close()
	items:=[]map[string]any{};for rows.Next(){var id,num,status,patientID,patient,branchID,branchName string;var employeeID,employee,specialty,roomID,roomNumber,appointmentID *string;var created time.Time;var called,starts *time.Time;var priority int;if rows.Scan(&id,&num,&status,&priority,&created,&called,&patientID,&patient,&employeeID,&employee,&specialty,&roomID,&roomNumber,&branchID,&branchName,&appointmentID,&starts)==nil{items=append(items,map[string]any{"id":id,"number":num,"status":status,"priority":priority,"createdAt":created,"calledAt":called,"patient":map[string]any{"id":patientID,"name":patient},"employee":map[string]any{"id":employeeID,"name":employee,"specialty":specialty},"room":map[string]any{"id":roomID,"number":roomNumber},"branch":map[string]any{"id":branchID,"name":branchName},"appointmentId":appointmentID,"startsAt":starts})}}
	writeJSON(w,200,map[string]any{"items":items})
}

type queueEntryInput struct {
	AppointmentID string `json:"appointmentId"`
	PatientID     string `json:"patientId"`
	EmployeeID    string `json:"employeeId"`
	RoomID        string `json:"roomId"`
	BranchID      string `json:"branchId"`
	Scope         string `json:"scope"`
	ScopeKey      string `json:"scopeKey"`
	Prefix        string `json:"prefix"`
	Priority      int    `json:"priority"`
}
func (a *App) createQueueEntry(w http.ResponseWriter,r *http.Request){var in queueEntryInput;if !decode(w,r,&in){return};p:=auth.PrincipalFrom(r.Context());if in.Scope==""{in.Scope="CLINIC"};if in.ScopeKey==""{in.ScopeKey="clinic"};in.Prefix=strings.ToUpper(strings.TrimSpace(in.Prefix));if len(in.Prefix)>3{errorJSON(w,422,"validation_error","Queue prefix is invalid",requestID(r));return}
	tx,e:=a.db.Begin(r.Context());if e!=nil{errorJSON(w,500,"database_error","Could not create queue entry",requestID(r));return};defer tx.Rollback(r.Context())
	if in.AppointmentID!=""{e=tx.QueryRow(r.Context(),`SELECT patient_id,employee_id,branch_id FROM appointments WHERE id=$1 AND organization_id=$2 AND status IN ('scheduled','confirmed','arrived')`,in.AppointmentID,p.OrganizationID).Scan(&in.PatientID,&in.EmployeeID,&in.BranchID);if e!=nil{errorJSON(w,422,"invalid_appointment","Appointment cannot be queued",requestID(r));return}}
	if _,e=uuid.Parse(in.PatientID);e!=nil{errorJSON(w,422,"invalid_patient","Patient is invalid",requestID(r));return};if _,e=uuid.Parse(in.BranchID);e!=nil{errorJSON(w,422,"invalid_branch","Branch is invalid",requestID(r));return}
	if _,e=tx.Exec(r.Context(),`SELECT pg_advisory_xact_lock(hashtext($1))`,p.OrganizationID+":"+in.BranchID+":"+in.ScopeKey);e!=nil{errorJSON(w,500,"database_error","Could not lock queue sequence",requestID(r));return}
	var seq int;e=tx.QueryRow(r.Context(),`SELECT COALESCE(max(sequence_number),0)+1 FROM queue_entries WHERE organization_id=$1 AND branch_id=$2 AND queue_date=(now() AT TIME ZONE 'Asia/Tashkent')::date AND scope_key=$3`,p.OrganizationID,in.BranchID,in.ScopeKey).Scan(&seq);if e!=nil{errorJSON(w,500,"database_error","Could not allocate queue number",requestID(r));return}
	id:=uuid.NewString();num:=fmt.Sprintf("%s%03d",in.Prefix,seq);_,e=tx.Exec(r.Context(),`INSERT INTO queue_entries(id,organization_id,branch_id,appointment_id,patient_id,employee_id,room_id,sequence_number,display_number,queue_scope,scope_key,priority,created_by) VALUES($1,$2,$3,NULLIF($4,'')::uuid,$5,NULLIF($6,'')::uuid,NULLIF($7,'')::uuid,$8,$9,$10,$11,$12,$13)`,id,p.OrganizationID,in.BranchID,in.AppointmentID,in.PatientID,in.EmployeeID,in.RoomID,seq,num,in.Scope,in.ScopeKey,in.Priority,p.UserID);if e!=nil{errorJSON(w,409,"queue_conflict","Patient is already queued or number conflict",requestID(r));return}
	_,_=tx.Exec(r.Context(),`UPDATE appointments SET status='arrived',updated_at=now() WHERE id=NULLIF($1,'')::uuid AND organization_id=$2`,in.AppointmentID,p.OrganizationID);_,_=tx.Exec(r.Context(),`INSERT INTO audit_logs(organization_id,branch_id,actor_id,action,entity_type,entity_id,result,changes) VALUES($1,$2,$3,'QUEUE_ENTRY_CREATED','queue_entry',$4,'success',jsonb_build_object('number',$5::text))`,p.OrganizationID,in.BranchID,p.UserID,id,num);if tx.Commit(r.Context())!=nil{errorJSON(w,500,"database_error","Could not commit queue entry",requestID(r));return};writeJSON(w,201,map[string]any{"id":id,"number":num,"status":"WAITING"})
}

func (a *App) callNextQueueEntry(w http.ResponseWriter,r *http.Request){var in struct{BranchID string `json:"branchId"`;EmployeeID string `json:"employeeId"`;RoomID string `json:"roomId"`};if !decode(w,r,&in){return};p:=auth.PrincipalFrom(r.Context());var id string;e:=a.db.QueryRow(r.Context(),`UPDATE queue_entries SET status='CALLED',room_id=COALESCE(NULLIF($4,'')::uuid,room_id),called_at=now(),updated_at=now() WHERE id=(SELECT id FROM queue_entries WHERE organization_id=$1 AND branch_id=$2 AND queue_date=(now() AT TIME ZONE 'Asia/Tashkent')::date AND status='WAITING' AND ($3='' OR employee_id::text=$3) ORDER BY priority DESC,sequence_number FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING id`,p.OrganizationID,in.BranchID,in.EmployeeID,in.RoomID).Scan(&id);if e!=nil{errorJSON(w,404,"queue_empty","No waiting patients",requestID(r));return};a.applyQueueAction(w,r,id,"call",in.RoomID)}
func (a *App) queueEntryAction(w http.ResponseWriter,r *http.Request){a.applyQueueAction(w,r,chi.URLParam(r,"id"),chi.URLParam(r,"action"),"")}
func (a *App) applyQueueAction(w http.ResponseWriter,r *http.Request,id,action,overrideRoom string){if _,e:=uuid.Parse(id);e!=nil{errorJSON(w,422,"invalid_id","Queue entry is invalid",requestID(r));return};states:=map[string]string{"call":"CALLED","recall":"RECALLED","start":"IN_SERVICE","complete":"COMPLETED","skip":"SKIPPED","cancel":"CANCELLED"};next,ok:=states[action];if !ok{errorJSON(w,422,"invalid_action","Queue action is invalid",requestID(r));return};p:=auth.PrincipalFrom(r.Context());tx,e:=a.db.Begin(r.Context());if e!=nil{errorJSON(w,500,"database_error","Could not update queue",requestID(r));return};defer tx.Rollback(r.Context())
	var org,branch,num,patient,doctor,specialty,room string;e=tx.QueryRow(r.Context(),`WITH changed AS (UPDATE queue_entries SET status=$1,room_id=COALESCE(NULLIF($2,'')::uuid,room_id),called_at=CASE WHEN $1 IN ('CALLED','RECALLED') THEN now() ELSE called_at END,service_started_at=CASE WHEN $1='IN_SERVICE' THEN now() ELSE service_started_at END,completed_at=CASE WHEN $1='COMPLETED' THEN now() ELSE completed_at END,updated_at=now() WHERE id=$3 AND organization_id=$4 RETURNING *) SELECT q.organization_id,q.branch_id,q.display_number,concat_ws(' ',p.last_name,p.first_name,p.middle_name),COALESCE(concat_ws(' ',e.last_name,e.first_name),''),COALESCE(e.specialty,''),COALESCE(rm.room_number,'') FROM changed q JOIN patients p ON p.id=q.patient_id LEFT JOIN employees e ON e.id=q.employee_id LEFT JOIN queue_rooms rm ON rm.id=q.room_id`,next,overrideRoom,id,p.OrganizationID).Scan(&org,&branch,&num,&patient,&doctor,&specialty,&room);if e!=nil{errorJSON(w,404,"not_found","Queue entry not found",requestID(r));return}
	callType:=strings.ToUpper(action);if action=="call"{callType="CALL"};_,e=tx.Exec(r.Context(),`INSERT INTO queue_call_history(organization_id,queue_entry_id,called_by,call_type,status,room_number) VALUES($1,$2,$3,$4,$5,NULLIF($6,''))`,org,id,p.UserID,callType,next,room);if e!=nil||tx.Commit(r.Context())!=nil{errorJSON(w,500,"database_error","Could not save queue action",requestID(r));return}
	event:=map[string]any{"type":"queue."+action,"entry":map[string]any{"id":id,"number":num,"status":next,"patient":patient,"doctor":doctor,"specialty":specialty,"room":room,"calledAt":time.Now()}};payload,_:=json.Marshal(event);rows,_:=a.db.Query(r.Context(),`SELECT id FROM queue_displays d WHERE organization_id=$1 AND branch_id=$2 AND is_active AND (NOT EXISTS(SELECT 1 FROM queue_display_rooms dr WHERE dr.display_id=d.id) OR EXISTS(SELECT 1 FROM queue_display_rooms dr JOIN queue_rooms rm ON rm.id=dr.room_id WHERE dr.display_id=d.id AND rm.room_number=$3))`,org,branch,room);if rows!=nil{defer rows.Close();for rows.Next(){var displayID string;if rows.Scan(&displayID)==nil{_ = a.redis.Publish(r.Context(),queueChannel(displayID),payload).Err()}}};a.log.Info("queue patient action","action",action,"queueEntryId",id,"number",num);writeJSON(w,200,event)
}

func (a *App) listQueueRooms(w http.ResponseWriter,r *http.Request){p:=auth.PrincipalFrom(r.Context());rows,e:=a.db.Query(r.Context(),`SELECT rm.id,rm.branch_id,b.name,rm.room_number,rm.name,rm.floor,rm.department,rm.employee_id,concat_ws(' ',e.last_name,e.first_name),rm.is_active FROM queue_rooms rm JOIN branches b ON b.id=rm.branch_id LEFT JOIN employees e ON e.id=rm.employee_id WHERE rm.organization_id=$1 ORDER BY b.name,rm.room_number`,p.OrganizationID);if e!=nil{errorJSON(w,500,"database_error","Could not load rooms",requestID(r));return};defer rows.Close();items:=[]map[string]any{};for rows.Next(){var id,bid,bn,num string;var name,department,eid,employee *string;var floor *int;var active bool;if rows.Scan(&id,&bid,&bn,&num,&name,&floor,&department,&eid,&employee,&active)==nil{items=append(items,map[string]any{"id":id,"branchId":bid,"branch":bn,"number":num,"name":name,"floor":floor,"department":department,"employeeId":eid,"employee":employee,"isActive":active})}};writeJSON(w,200,map[string]any{"items":items})}
func (a *App) saveQueueRoom(w http.ResponseWriter,r *http.Request){var in struct{BranchID string `json:"branchId"`;Number string `json:"number"`;Name string `json:"name"`;Department string `json:"department"`;EmployeeID string `json:"employeeId"`;Floor *int `json:"floor"`;IsActive *bool `json:"isActive"`};if !decode(w,r,&in){return};in.Number=strings.TrimSpace(in.Number);if _,e:=uuid.Parse(in.BranchID);e!=nil||in.Number==""{errorJSON(w,422,"validation_error","Room fields are invalid",requestID(r));return};p:=auth.PrincipalFrom(r.Context());id:=chi.URLParam(r,"id");if id==""{id=uuid.NewString()};active:=true;if in.IsActive!=nil{active=*in.IsActive};tag,e:=a.db.Exec(r.Context(),`INSERT INTO queue_rooms(id,organization_id,branch_id,room_number,name,floor,department,employee_id,is_active) VALUES($1,$2,$3,$4,NULLIF($5,''),$6,NULLIF($7,''),NULLIF($8,'')::uuid,$9) ON CONFLICT(id) DO UPDATE SET branch_id=EXCLUDED.branch_id,room_number=EXCLUDED.room_number,name=EXCLUDED.name,floor=EXCLUDED.floor,department=EXCLUDED.department,employee_id=EXCLUDED.employee_id,is_active=EXCLUDED.is_active,updated_at=now() WHERE queue_rooms.organization_id=$2`,id,p.OrganizationID,in.BranchID,in.Number,in.Name,in.Floor,in.Department,in.EmployeeID,active);if e!=nil||tag.RowsAffected()==0{errorJSON(w,409,"room_conflict","Could not save room",requestID(r));return};writeJSON(w,200,map[string]any{"id":id})}

func (a *App) listQueueDisplays(w http.ResponseWriter,r *http.Request){p:=auth.PrincipalFrom(r.Context());rows,e:=a.db.Query(r.Context(),`SELECT d.id,d.branch_id,b.name,d.name,d.slug,d.token_prefix,d.is_active,d.language,d.voice_language,d.privacy_mode,d.settings,d.created_at FROM queue_displays d JOIN branches b ON b.id=d.branch_id WHERE d.organization_id=$1 ORDER BY d.name`,p.OrganizationID);if e!=nil{errorJSON(w,500,"database_error","Could not load displays",requestID(r));return};defer rows.Close();items:=[]map[string]any{};for rows.Next(){var id,bid,bn,name,slug,prefix,language,voice,privacy string;var active bool;var settings json.RawMessage;var created time.Time;if rows.Scan(&id,&bid,&bn,&name,&slug,&prefix,&active,&language,&voice,&privacy,&settings,&created)==nil{items=append(items,map[string]any{"id":id,"branchId":bid,"branch":bn,"name":name,"slug":slug,"tokenPrefix":prefix,"isActive":active,"language":language,"voiceLanguage":voice,"privacyMode":privacy,"settings":settings,"createdAt":created})}};writeJSON(w,200,map[string]any{"items":items,"displayBaseUrl":a.cfg.QueueDisplayURL})}
type displayInput struct{BranchID string `json:"branchId"`;Name string `json:"name"`;Slug string `json:"slug"`;Language string `json:"language"`;VoiceLanguage string `json:"voiceLanguage"`;PrivacyMode string `json:"privacyMode"`;IsActive *bool `json:"isActive"`;Settings json.RawMessage `json:"settings"`}
func (a *App) createQueueDisplay(w http.ResponseWriter,r *http.Request){var in displayInput;if !decode(w,r,&in){return};in.Slug=strings.ToLower(strings.TrimSpace(in.Slug));if !queueSlugPattern.MatchString(in.Slug){errorJSON(w,422,"validation_error","Display slug is invalid",requestID(r));return};p:=auth.PrincipalFrom(r.Context());token:=newDisplayToken();id:=uuid.NewString();_,e:=a.db.Exec(r.Context(),`INSERT INTO queue_displays(id,organization_id,branch_id,name,slug,token_hash,token_prefix,language,voice_language,privacy_mode,settings,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,CASE WHEN $11='' THEN '{"primaryColor":"#e80d4f","secondaryColor":"#17202a","backgroundColor":"#f7f9fb","textColor":"#17202a","showDoctor":true,"showSpecialty":true,"showClock":true,"showDate":true,"showSeconds":false,"showMedia":true,"showTicker":true,"showRecentCalls":true,"recentCallCount":5,"callDisplaySeconds":12,"videoCallMode":"OVERLAY","videoAnnouncementVolume":0}'::jsonb ELSE $11::jsonb END,$12)`,id,p.OrganizationID,in.BranchID,strings.TrimSpace(in.Name),in.Slug,tokenHash(token),token[:8],defaultString(in.Language,"ru"),defaultString(in.VoiceLanguage,"ru"),defaultString(in.PrivacyMode,"NUMBER_ONLY"),string(in.Settings),p.UserID);if e!=nil{errorJSON(w,409,"display_conflict","Could not create display",requestID(r));return};writeJSON(w,201,map[string]any{"id":id,"token":token,"url":strings.TrimRight(a.cfg.QueueDisplayURL,"/")+"/"+token})}
func defaultString(v,d string)string{if strings.TrimSpace(v)==""{return d};return v}
func (a *App) updateQueueDisplay(w http.ResponseWriter,r *http.Request){id:=chi.URLParam(r,"id");var in displayInput;if !decode(w,r,&in){return};p:=auth.PrincipalFrom(r.Context());active:=true;if in.IsActive!=nil{active=*in.IsActive};tag,e:=a.db.Exec(r.Context(),`UPDATE queue_displays SET branch_id=$1,name=$2,slug=$3,is_active=$4,language=$5,voice_language=$6,privacy_mode=$7,settings=settings||COALESCE(NULLIF($8,'')::jsonb,'{}'::jsonb),updated_at=now() WHERE id=$9 AND organization_id=$10`,in.BranchID,in.Name,in.Slug,active,in.Language,in.VoiceLanguage,in.PrivacyMode,string(in.Settings),id,p.OrganizationID);if e!=nil||tag.RowsAffected()==0{errorJSON(w,404,"not_found","Display not found",requestID(r));return};writeJSON(w,200,map[string]bool{"ok":true})}
func (a *App) rotateQueueDisplayToken(w http.ResponseWriter,r *http.Request){p:=auth.PrincipalFrom(r.Context());token:=newDisplayToken();tag,e:=a.db.Exec(r.Context(),`UPDATE queue_displays SET token_hash=$1,token_prefix=$2,updated_at=now() WHERE id=$3 AND organization_id=$4`,tokenHash(token),token[:8],chi.URLParam(r,"id"),p.OrganizationID);if e!=nil||tag.RowsAffected()==0{errorJSON(w,404,"not_found","Display not found",requestID(r));return};writeJSON(w,200,map[string]any{"token":token,"url":strings.TrimRight(a.cfg.QueueDisplayURL,"/")+"/"+token})}

func (a *App) resolveDisplay(r *http.Request)(string,string,error){token:=chi.URLParam(r,"token");var id,org string;e:=a.db.QueryRow(r.Context(),`SELECT id,organization_id FROM queue_displays WHERE token_hash=$1 AND is_active`,tokenHash(token)).Scan(&id,&org);return id,org,e}
func (a *App) getQueueDisplayState(w http.ResponseWriter,r *http.Request){displayID,org,e:=a.resolveDisplay(r);if e!=nil{errorJSON(w,404,"display_not_found","Display not found",requestID(r));return};state,e:=a.queueDisplayState(r,displayID,org);if e!=nil{errorJSON(w,500,"database_error","Could not load display",requestID(r));return};writeJSON(w,200,state)}
func (a *App) queueDisplayState(r *http.Request,displayID,org string)(map[string]any,error){var name,language,voice,privacy string;var settings json.RawMessage;e:=a.db.QueryRow(r.Context(),`SELECT name,language,voice_language,privacy_mode,settings FROM queue_displays WHERE id=$1 AND organization_id=$2`,displayID,org).Scan(&name,&language,&voice,&privacy,&settings);if e!=nil{return nil,e};rows,e:=a.db.Query(r.Context(),`SELECT q.id,q.display_number,q.status,COALESCE(rm.room_number,''),COALESCE(concat_ws(' ',em.last_name,em.first_name),''),COALESCE(em.specialty,''),p.first_name,p.last_name,q.called_at FROM queue_entries q JOIN patients p ON p.id=q.patient_id LEFT JOIN employees em ON em.id=q.employee_id LEFT JOIN queue_rooms rm ON rm.id=q.room_id JOIN queue_displays d ON d.id=$1 AND d.organization_id=q.organization_id AND d.branch_id=q.branch_id WHERE q.organization_id=$2 AND q.queue_date=(now() AT TIME ZONE 'Asia/Tashkent')::date AND q.status IN ('CALLED','RECALLED','IN_SERVICE') AND (NOT EXISTS(SELECT 1 FROM queue_display_rooms dr WHERE dr.display_id=d.id) OR q.room_id IN (SELECT room_id FROM queue_display_rooms WHERE display_id=d.id)) ORDER BY q.called_at DESC NULLS LAST LIMIT 15`,displayID,org);if e!=nil{return nil,e};defer rows.Close();calls:=[]map[string]any{};for rows.Next(){var id,num,status,room,doctor,specialty,first,last string;var called *time.Time;if rows.Scan(&id,&num,&status,&room,&doctor,&specialty,&first,&last,&called)==nil{nameValue:="";if privacy=="FIRST_NAME_INITIAL"{nameValue=first+" "+firstRune(last)+"."};if privacy=="FULL_NAME"{nameValue=last+" "+first};calls=append(calls,map[string]any{"id":id,"number":num,"status":status,"room":room,"doctor":doctor,"specialty":specialty,"patient":nameValue,"calledAt":called})}};var tickers []string;_ = a.db.QueryRow(r.Context(),`SELECT COALESCE(array_agg(text ORDER BY sort_order),'{}') FROM queue_ticker_messages WHERE organization_id=$1 AND language=$2 AND is_active AND (starts_at IS NULL OR starts_at<=now()) AND (ends_at IS NULL OR ends_at>=now())`,org,language).Scan(&tickers);return map[string]any{"displayId":displayID,"name":name,"language":language,"voiceLanguage":voice,"privacyMode":privacy,"settings":settings,"calls":calls,"tickers":tickers,"media":a.publicQueueMedia(r,displayID,org)},nil}

func (a *App) publicQueueMedia(r *http.Request,displayID,org string) []map[string]any { rows,e:=a.db.Query(r.Context(),`SELECT m.id,m.kind,m.title,m.asset_key,m.language,m.content_type,m.duration_seconds FROM queue_media_assets m WHERE m.organization_id=$1 AND m.is_active AND (m.starts_at IS NULL OR m.starts_at<=now()) AND (m.ends_at IS NULL OR m.ends_at>=now()) AND (NOT EXISTS(SELECT 1 FROM queue_display_media WHERE display_id=$2) OR EXISTS(SELECT 1 FROM queue_display_media dm WHERE dm.display_id=$2 AND dm.media_id=m.id)) ORDER BY COALESCE((SELECT sort_order FROM queue_display_media WHERE display_id=$2 AND media_id=m.id),m.sort_order),m.created_at`,org,displayID);if e!=nil{return []map[string]any{}};defer rows.Close();items:=[]map[string]any{};for rows.Next(){var id,kind,title,contentType string;var key,language *string;var duration *int;if rows.Scan(&id,&kind,&title,&key,&language,&contentType,&duration)==nil{items=append(items,map[string]any{"id":id,"kind":kind,"title":title,"assetKey":key,"language":language,"contentType":contentType,"durationSeconds":duration})}};return items}
func firstRune(v string)string{r:=[]rune(v);if len(r)==0{return ""};return string(r[0])}
func (a *App) streamQueueDisplay(w http.ResponseWriter,r *http.Request){displayID,_,e:=a.resolveDisplay(r);if e!=nil{errorJSON(w,404,"display_not_found","Display not found",requestID(r));return};flusher,ok:=w.(http.Flusher);if !ok{errorJSON(w,500,"stream_unsupported","Streaming unsupported",requestID(r));return};w.Header().Set("Content-Type","text/event-stream");w.Header().Set("Cache-Control","no-cache");w.Header().Set("Connection","keep-alive");sub:=a.redis.Subscribe(r.Context(),queueChannel(displayID));defer sub.Close();fmt.Fprint(w,"event: connected\ndata: {}\n\n");flusher.Flush();a.log.Info("queue display connected","displayId",displayID);keep:=time.NewTicker(20*time.Second);defer keep.Stop();for{select{case <-r.Context().Done():return;case msg:=<-sub.Channel():fmt.Fprintf(w,"event: queue\ndata: %s\n\n",msg.Payload);flusher.Flush();case <-keep.C:fmt.Fprint(w,": keepalive\n\n");flusher.Flush()}}}
func (a *App) listQueueHistory(w http.ResponseWriter,r *http.Request){p:=auth.PrincipalFrom(r.Context());limit:=100;if n,e:=strconv.Atoi(r.URL.Query().Get("limit"));e==nil&&n>0&&n<=500{limit=n};rows,e:=a.db.Query(r.Context(),`SELECT h.id,h.call_type,h.status,h.room_number,h.created_at,q.display_number,concat_ws(' ',pt.last_name,pt.first_name),concat_ws(' ',em.last_name,em.first_name),concat_ws(' ',caller.last_name,caller.first_name) FROM queue_call_history h JOIN queue_entries q ON q.id=h.queue_entry_id JOIN patients pt ON pt.id=q.patient_id LEFT JOIN employees em ON em.id=q.employee_id LEFT JOIN employees caller ON caller.user_id=h.called_by WHERE h.organization_id=$1 ORDER BY h.created_at DESC LIMIT $2`,p.OrganizationID,limit);if e!=nil{errorJSON(w,500,"database_error","Could not load history",requestID(r));return};defer rows.Close();items:=[]map[string]any{};for rows.Next(){var id int64;var typ,status,num,patient,doctor,caller string;var room *string;var created time.Time;if rows.Scan(&id,&typ,&status,&room,&created,&num,&patient,&doctor,&caller)==nil{items=append(items,map[string]any{"id":id,"type":typ,"status":status,"room":room,"createdAt":created,"number":num,"patient":patient,"doctor":doctor,"caller":caller})}};writeJSON(w,200,map[string]any{"items":items})}
