package app

import (
	"net/http"
	"time"

	"clinicos/api/internal/auth"
	"github.com/google/uuid"
)

func (a *App) getReportSummary(w http.ResponseWriter, r *http.Request) {
	p := auth.PrincipalFrom(r.Context())
	now := time.Now().In(time.FixedZone("UZT", 5*60*60)); from := time.Date(now.Year(),now.Month(),1,0,0,0,0,now.Location()); to := from.AddDate(0,1,0)
	if value:=r.URL.Query().Get("from"); value!="" { parsed,err:=time.Parse("2006-01-02",value); if err!=nil { errorJSON(w,422,"invalid_period","Invalid start date",requestID(r));return }; from=parsed }
	if value:=r.URL.Query().Get("to"); value!="" { parsed,err:=time.Parse("2006-01-02",value); if err!=nil { errorJSON(w,422,"invalid_period","Invalid end date",requestID(r));return }; to=parsed.AddDate(0,0,1) }
	if !to.After(from)||to.Sub(from)>366*24*time.Hour { errorJSON(w,422,"invalid_period","Period must be between 1 and 366 days",requestID(r));return }
	branchID:=r.URL.Query().Get("branchId"); if branchID!="" { if _,err:=uuid.Parse(branchID);err!=nil{errorJSON(w,422,"invalid_branch","Invalid branch",requestID(r));return} }
	var patients,appointments,completed,cancelled,noShow,activeEmployees,bedTotal,bedOccupied,admissions int64; var inpatientRevenue int64
	_ = a.db.QueryRow(r.Context(),`SELECT count(*) FROM patients WHERE organization_id=$1 AND deleted_at IS NULL AND created_at>=$2 AND created_at<$3 AND ($4='' OR home_branch_id=NULLIF($4,'')::uuid)`,p.OrganizationID,from,to,branchID).Scan(&patients)
	_ = a.db.QueryRow(r.Context(),`SELECT count(*),count(*) FILTER(WHERE status='completed'),count(*) FILTER(WHERE status='cancelled'),count(*) FILTER(WHERE status='no_show') FROM appointments WHERE organization_id=$1 AND starts_at>=$2 AND starts_at<$3 AND ($4='' OR branch_id=NULLIF($4,'')::uuid)`,p.OrganizationID,from,to,branchID).Scan(&appointments,&completed,&cancelled,&noShow)
	_ = a.db.QueryRow(r.Context(),`SELECT count(*) FROM employees e JOIN users u ON u.id=e.user_id WHERE e.organization_id=$1 AND u.is_active=true AND u.deleted_at IS NULL AND ($2='' OR e.branch_id=NULLIF($2,'')::uuid)`,p.OrganizationID,branchID).Scan(&activeEmployees)
	_ = a.db.QueryRow(r.Context(),`SELECT count(*) FROM inpatient_beds bd JOIN inpatient_rooms rm ON rm.id=bd.room_id WHERE bd.organization_id=$1 AND bd.is_active=true AND rm.is_active=true AND ($2='' OR rm.branch_id=NULLIF($2,'')::uuid)`,p.OrganizationID,branchID).Scan(&bedTotal)
	_ = a.db.QueryRow(r.Context(),`SELECT count(DISTINCT bed_id) FROM inpatient_bookings WHERE organization_id=$1 AND status='CHECKED_IN' AND check_in<=now() AND check_out>now() AND ($2='' OR branch_id=NULLIF($2,'')::uuid)`,p.OrganizationID,branchID).Scan(&bedOccupied)
	_ = a.db.QueryRow(r.Context(),`SELECT count(*),COALESCE(sum(GREATEST(1,ceil(extract(epoch FROM (check_out-check_in))/86400))::bigint*price_per_day_uzs-discount_uzs),0) FROM inpatient_bookings WHERE organization_id=$1 AND status<>'CANCELLED' AND check_in>=$2 AND check_in<$3 AND ($4='' OR branch_id=NULLIF($4,'')::uuid)`,p.OrganizationID,from,to,branchID).Scan(&admissions,&inpatientRevenue)
	statuses:=[]map[string]any{}; rows,_:=a.db.Query(r.Context(),`SELECT status,count(*) FROM appointments WHERE organization_id=$1 AND starts_at>=$2 AND starts_at<$3 AND ($4='' OR branch_id=NULLIF($4,'')::uuid) GROUP BY status ORDER BY status`,p.OrganizationID,from,to,branchID); if rows!=nil { defer rows.Close();for rows.Next(){var status string;var count int64;if rows.Scan(&status,&count)==nil{statuses=append(statuses,map[string]any{"status":status,"count":count})}} }
	daily:=[]map[string]any{}; dayRows,_:=a.db.Query(r.Context(),`SELECT starts_at::date,count(*),count(*) FILTER(WHERE status='completed') FROM appointments WHERE organization_id=$1 AND starts_at>=$2 AND starts_at<$3 AND ($4='' OR branch_id=NULLIF($4,'')::uuid) GROUP BY starts_at::date ORDER BY starts_at::date`,p.OrganizationID,from,to,branchID);if dayRows!=nil{defer dayRows.Close();for dayRows.Next(){var day time.Time;var count,done int64;if dayRows.Scan(&day,&count,&done)==nil{daily=append(daily,map[string]any{"date":day.Format("2006-01-02"),"appointments":count,"completed":done})}}}
	doctors:=[]map[string]any{}; doctorRows,_:=a.db.Query(r.Context(),`SELECT e.id,e.last_name||' '||e.first_name,count(a.id),count(a.id) FILTER(WHERE a.status='completed') FROM employees e JOIN users u ON u.id=e.user_id LEFT JOIN appointments a ON a.employee_id=e.id AND a.starts_at>=$2 AND a.starts_at<$3 WHERE e.organization_id=$1 AND u.deleted_at IS NULL AND ($4='' OR e.branch_id=NULLIF($4,'')::uuid) GROUP BY e.id ORDER BY count(a.id) DESC,e.last_name LIMIT 30`,p.OrganizationID,from,to,branchID);if doctorRows!=nil{defer doctorRows.Close();for doctorRows.Next(){var id,name string;var count,done int64;if doctorRows.Scan(&id,&name,&count,&done)==nil{doctors=append(doctors,map[string]any{"id":id,"name":name,"appointments":count,"completed":done})}}}
	branches:=[]map[string]any{}; branchRows,_:=a.db.Query(r.Context(),`SELECT b.id,b.name,count(DISTINCT a.id),count(DISTINCT pt.id),count(DISTINCT e.id) FILTER(WHERE u.is_active=true AND u.deleted_at IS NULL) FROM branches b LEFT JOIN appointments a ON a.branch_id=b.id AND a.starts_at>=$2 AND a.starts_at<$3 LEFT JOIN patients pt ON pt.home_branch_id=b.id AND pt.created_at>=$2 AND pt.created_at<$3 AND pt.deleted_at IS NULL LEFT JOIN employees e ON e.branch_id=b.id LEFT JOIN users u ON u.id=e.user_id WHERE b.organization_id=$1 AND b.deleted_at IS NULL AND ($4='' OR b.id=NULLIF($4,'')::uuid) GROUP BY b.id ORDER BY b.name`,p.OrganizationID,from,to,branchID);if branchRows!=nil{defer branchRows.Close();for branchRows.Next(){var id,name string;var ap,pt,em int64;if branchRows.Scan(&id,&name,&ap,&pt,&em)==nil{branches=append(branches,map[string]any{"id":id,"name":name,"appointments":ap,"newPatients":pt,"employees":em})}}}
	writeJSON(w,200,map[string]any{"period":map[string]string{"from":from.Format("2006-01-02"),"to":to.AddDate(0,0,-1).Format("2006-01-02")},"summary":map[string]any{"newPatients":patients,"appointments":appointments,"completed":completed,"cancelled":cancelled,"noShow":noShow,"activeEmployees":activeEmployees,"bedTotal":bedTotal,"bedOccupied":bedOccupied,"admissions":admissions,"inpatientRevenueUzs":inpatientRevenue},"appointmentStatuses":statuses,"daily":daily,"doctors":doctors,"branches":branches})
}
